Safe-DS/DSL

package.json

Use my configuration for prettier.

ci: configure prettier

---

.github/workflows/issue.yml

Issues created in this repository will now be automatically added to the "General" project.

ci: workflow to add issues to General project

---

.github/workflows/release.yml
DSL/com.larsreimann.safeds.vscode/build.gradle.kts
DSL/com.larsreimann.safeds.vscode/package-lock.json
DSL/com.larsreimann.safeds.vscode/package.json

Closes #46.
Add a new workflow to publish the VS Code extension to the marketplace.

ci: release to vs code marketplace

---

.github/workflows/release.yml
DSL/build.gradle.kts
DSL/com.larsreimann.safeds/build.gradle.kts

Closes #47.
Add workflow to release the core Jar of the DSL to Maven Central.

ci: release to Maven Central

---

DSL/build.gradle.kts
DSL/com.larsreimann.safeds.vscode/package-lock.json
DSL/com.larsreimann.safeds.vscode/package.json
Runtime/safe-ds-runner/pyproject.toml
Runtime/safe-ds/pyproject.toml

chore: bump version numbers to 1.0.0

---

DSL/com.larsreimann.safeds/build.gradle.kts

* Add dependency from `dokkaHtml` task to `generateXtextLanguage`

build: fix issues when creating HTML documentation

---

Runtime/safe-ds/safe_ds/data/_table.py
Runtime/safe-ds/tests/data/_table/test_add_column.py
Runtime/safe-ds/tests/data/_table/test_add_columns.py
Runtime/safe-ds/tests/data/_table/test_add_rows.py

Closes #311.
Added function to add multiple rows to a table given as a list of rows.
Added function to add multiple rows to a table given as another table with matching schemas.
Added function to add multiple columns to a table given as a list of columns.
Added function to add multiple columns to a table given as another table with matching row-counts.

feat: Added methods add_rows and add_columns in Table for list of Rows/Columns and Table

---

Runtime/safe-ds/safe_ds/data/_table.py
Runtime/safe-ds/safe_ds/exceptions/__init__.py
Runtime/safe-ds/safe_ds/exceptions/_data_exceptions.py

Closes #306 .
Added ability to provide a TableSchema in the Table constructor

feat: Added ability to provide a TableSchema in the Table constructor

---

Runtime/safe-ds/safe_ds/data/_table.py
Runtime/safe-ds/tests/data/_table/test_shuffle.py
Runtime/safe-ds/tests/data/_table/test_slice.py
Runtime/safe-ds/tests/data/_table/test_split.py

Closes #302 
Added slice(start, end, step), split(percentage) and shuffle() to Table

feat: added slice, split and shuffle to table

---

mkdocs.yml

Show link to repo in header of documentation.

docs: add repo URL

---

.github/workflows/publish_stdlib_to_pypi.yml
Runtime/safe-ds/pyproject.toml

Workflow to publish the standard library to PyPI.

ci: add a workflow to publish the stdlib to PyPI

---

mkdocs.yml

Toggle between a light and dark mode in the documentation.

docs: add dark mode

---

Runtime/safe-ds/safe_ds/plotting/_plot_boxplot.py
Runtime/safe-ds/safe_ds/plotting/_plot_correlation_heatmap.py
Runtime/safe-ds/safe_ds/plotting/_plot_histogram.py

Closes #355 .
Now correct labels and rotation for heatmap.

fix: some plotting methods wrong labels

---

docs/DSL/pipeline-language/expressions.md
docs/javascript/mathjax.js
mkdocs.yml
tsconfig.eslint.json

* Single page application
* Admonitions
* Various markdown extensions
* MathJax
* Buttons to copy code

docs: configure various features of material for mkdocs

---

Runtime/safe-ds/safe_ds/classification/metrics/_module_level_functions.py
Runtime/safe-ds/safe_ds/data/_ordinal_encoder.py

Closes #376 .
Standardizes OrdinalEncoder docstrings.
(Piggybacked on the issue to fix Accuracy docstring as well)

fix: changed OrdinalEncoder docstrings

---

.mega-linter.yml
mkdocs.yml

Add button to the right of headings to navigate to a permalink that points exactly to that heading.

docs: permalinks to headings

---

docs/requirements.txt
mkdocs.yml

Click on images to show them in full size.

docs: image zoom

---

Runtime/safe-ds/safeds/data/_label_encoder.py
Runtime/safe-ds/safeds/data/_ordinal_encoder.py
Runtime/safe-ds/safeds/data/tabular/_column.py
Runtime/safe-ds/safeds/ml/regression/metrics/_module_level_functions.py
docs/Stdlib/python/Tutorials/machine_learning.md

Closes #384.
Fix all formatting issues in the documentation that cause griffe warnings.

docs: fix griffe warnings

---

Runtime/safe-ds/safeds/data/_imputer.py
Runtime/safe-ds/safeds/data/_label_encoder.py
Runtime/safe-ds/safeds/data/_one_hot_encoder.py
Runtime/safe-ds/safeds/data/_ordinal_encoder.py
Runtime/safe-ds/safeds/data/tabular/_column.py
Runtime/safe-ds/safeds/exceptions/_data_exceptions.py

Closes #390.
* Add missing underscore prefix to internal instance attributes

fix: ensure names of instance attributes start with an underscore

---

Runtime/safe-ds/tests/data/tabular/_table/test_summary.py
docs/Stdlib/python/Tutorials/data_processing.md
docs/Stdlib/python/Tutorials/machine_learning.md
docs/Stdlib/python/Tutorials/visualization.md

Fixed grammatical errors, changed phrasing to sound less German and be more explanatory. Tried to refrain from using "you" in short explanations (in line with auto-generated docs from docstrings).

docs: proofreading for docs

---

docs/Stdlib/python/Tutorials/visualization.md

Added some missing references in documentation.

docs: missing references in visualization

---

codecov.yml

Codecov didn't pick up the coverage from the DSL component in #434.

ci: configure codecov

---

CITATION.cff

docs: add citation file

---

esbuild.mjs
src/helpers/resources.ts
src/language/builtins/fileFinder.ts
src/language/builtins/safe-ds-annotations.ts
src/language/builtins/safe-ds-classes.ts
src/language/workspace/safe-ds-workspace-manager.ts
src/resources/builtins/safeds/lang/codeGeneration.sdsstub
src/resources/builtins/safeds/lang/coreAnnotations.sdsstub
src/resources/builtins/safeds/lang/documentation.sdsstub
tests/helpers/resources.test.ts
tests/helpers/testResources.test.ts
tests/helpers/testResources.ts
tests/language/builtins/builtinFilesCorrectness.test.ts
tests/language/builtins/fileFinder.test.ts
tests/language/formatting/creator.ts
tests/language/generation/creator.ts
tests/language/grammar/creator.ts
tests/language/partialEvaluation/creator.ts
tests/language/scoping/creator.ts
tests/language/typing/creator.ts
tests/language/validation/creator.ts

Ensure that builtin files have neither errors nor warnings.

test: builtin files should not have errors or warnings

---

src/language/formatting/safe-ds-formatter.ts
src/language/grammar/safe-ds.langium
src/language/scoping/safe-ds-scope-provider.ts
src/language/validation/safe-ds-validator.ts
src/language/validation/style.ts
tests/resources/validation/style/unnecessary import alias/main.sdstest
tests/resources/validation/style/unnecessary import alias/resources.sdstest

Closes #636
Show an info if the import alias is identical to the declaration name.

feat: info if import alias can be removed

---

.github/README.md
.github/workflows/release.yml
.vscodeignore
README.md
bin/cli.js
esbuild.mjs
package-lock.json
package.json
release.config.cjs
src/extension/main.ts
tsconfig.eslint.json
vitest.config.ts

Closes #71
Configure `semantic-release` to ease the release of new versions.

ci: release with `semantic-release`

---

packages/safe-ds-lang/src/language/helpers/safe-ds-node-mapper.ts
packages/safe-ds-lang/src/language/typing/model.ts
packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts
packages/safe-ds-lang/tests/language/typing/model.test.ts

Add tests for the model classes for types.

test: model classes for types

---

packages/safe-ds-lang/src/language/validation/other/declarations/segments.ts
packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts
packages/safe-ds-lang/tests/resources/validation/other/declarations/segments/unused/main.sdstest
packages/safe-ds-lang/tests/resources/validation/other/declarations/segments/unused/same package.sdstest

Closes #682
Show a warning if internal/private segments are unused and mark them as unnecessary.

feat: mark unused internal/private segments as unnecessary

---

package-lock.json
packages/safe-ds-cli/package.json
packages/safe-ds-lang/package.json
packages/safe-ds-lang/src/language/lsp/safe-ds-semantic-token-provider.ts
packages/safe-ds-vscode/package.json

Bump Langium to version `2.1.0`.

build: bump langium to the latest version

---

packages/safe-ds-lang/src/language/partialEvaluation/model.ts
packages/safe-ds-lang/src/language/partialEvaluation/safe-ds-partial-evaluator.ts
packages/safe-ds-lang/tests/language/partialEvaluation/model.test.ts
packages/safe-ds-lang/tests/resources/partial evaluation/base cases/block lambdas/main.sdstest
packages/safe-ds-lang/tests/resources/partial evaluation/base cases/expression lambdas/main.sdstest
packages/safe-ds-lang/tests/resources/partial evaluation/base cases/segments/main.sdstest
packages/safe-ds-lang/tests/resources/partial evaluation/invalid nodes/main.sdstest

Closes partially #603
Partially evaluate lambdas and segments.

feat: partially evaluate lambdas and segments

---

packages/safe-ds-lang/src/language/lsp/safe-ds-type-hierarchy-provider.ts

Clean up the code for the type hierarchy provider.

refactor: clean up type hierarchy provider

---

docs/language/common/comments.md

Closes partially #669
Document how to write documentation comments.

docs: documentation comments

---

packages/safe-ds-vscode/snippets/safe-ds.json

Update snippets for functions and methods to include calls of purity annotations.

feat: update snippets for functions and methods

---

package-lock.json
package.json
packages/safe-ds-cli/package.json
packages/safe-ds-lang/package.json
packages/safe-ds-vscode/README.md
packages/safe-ds-vscode/package.json

Bump dependencies to latest usable version.

build: bump dependencies

---

packages/safe-ds-lang/src/language/partialEvaluation/model.ts
packages/safe-ds-lang/src/language/partialEvaluation/safe-ds-partial-evaluator.ts
packages/safe-ds-lang/src/language/validation/other/expressions/indexedAccess.ts
packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts
packages/safe-ds-lang/tests/resources/validation/other/expressions/indexed access/list index out of bounds/main.sdstest
packages/safe-ds-lang/tests/resources/validation/other/expressions/indexed access/map key does not exist/main.sdstest

Closes #16
* Show an error if we know that a map key does not exist.
* Show an error if we know that a list index is out of bounds.

feat: error if index of indexed access is invalid

---

packages/safe-ds-cli/src/cli/format.ts
packages/safe-ds-cli/src/cli/main.ts
packages/safe-ds-cli/src/helpers/diagnostics.ts
packages/safe-ds-cli/tests/cli/main.test.ts
packages/safe-ds-cli/tests/resources/format/contains syntax errors.sdstest
packages/safe-ds-cli/tests/resources/format/correct.sdstest
packages/safe-ds-cli/tests/resources/format/not safe-ds.txt

Closes #702
Add a new `format` command to format Safe-DS files.

feat: CLI command to run formatting

---

packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts

`computeType` takes type parameter substitutions as an argument, which get applied before the result is returned. Previously, the substitutions were used as they were given. Now they get simplified before they are applied.

feat: simplify substitutions passed to `computeType`

---

package-lock.json
packages/safe-ds-vscode/package.json

Downgrade `vsce` to `v2.22.0` while https://github.com/microsoft/vscode-vsce/issues/929 is open.

build: downgrade `vsce` to `v2.22.0`

---

packages/safe-ds-lang/src/language/grammar/safe-ds.langium
packages/safe-ds-lang/src/language/lsp/safe-ds-formatter.ts
packages/safe-ds-lang/src/language/scoping/safe-ds-scope-computation.ts
packages/safe-ds-lang/tests/resources/formatting/declarations/segments/with constraint list.sdstest
packages/safe-ds-lang/tests/resources/grammar/declarations/segments/good-with constraint list.sdstest
packages/safe-ds-lang/tests/resources/scoping/parameter bounds/in segment/main.sdstest
packages/safe-ds-lang/tests/resources/validation/style/unnecessary constraint list in segment/main.sdstest

Closes #903
Segments can now have constraint lists.

feat: constraints for segments

---

packages/safe-ds-lang/src/language/runner/safe-ds-runner.ts
packages/safe-ds-vscode/src/extension/mainClient.ts

Closes #909
- failing to start runner process now logs an appropriate message informs the user via popup again
- command is now successfully passed to the runner component, if changed

fix: runner startup silent failure

---

packages/safe-ds-vscode/package.json
packages/safe-ds-vscode/src/extension/mainClient.ts

Save dirty files before running a pipeline. Previously, the last saved state was executed.

fix: save dirty files before running pipeline

---

packages/safe-ds-lang/src/language/runner/safe-ds-runner.ts
packages/safe-ds-vscode/src/extension/mainClient.ts

- pipeline name is now passed to execution to allow execution of multiple pipelines

refactor: pass pipeline name for runner execution

---

packages/safe-ds-lang/src/language/documentation/safe-ds-comment-provider.ts
packages/safe-ds-lang/src/language/lsp/safe-ds-inlay-hint-provider.ts
packages/safe-ds-lang/src/language/validation/builtins/experimental.ts
packages/safe-ds-lang/src/language/validation/experimentalLanguageFeatures.ts
packages/safe-ds-lang/src/language/workspace/safe-ds-settings-provider.ts
packages/safe-ds-lang/src/resources/builtins/safeds/data/tabular/containers/column.sdsstub
packages/safe-ds-vscode/package.json

Inlay hints for 
* parameter names
* assignee types
can now be turned on/off individually.

feat: add settings to enable inlay hints individually

---

packages/safe-ds-lang/src/resources/builtins/safeds/lang/coreClasses.sdsstub

Add stubs to convert numbers and strings to ints.

feat: stubs for int conversions

---

docs/stdlib/safeds/data/tabular/containers/Column.md
docs/stdlib/safeds/lang/Float.md
docs/stdlib/safeds/lang/Int.md
docs/stdlib/safeds/lang/List.md
docs/stdlib/safeds/lang/Map.md
docs/stdlib/safeds/lang/Number.md
docs/stdlib/safeds/lang/String.md
package.json
packages/safe-ds-lang/src/resources/builtins/safeds/lang/coreClasses.sdsstub

* Add `Int.toFloat` and `String.toFloat`
* Update the documentation for the standard library
* Add an NPM script to do so more easily in the future

feat: add `toFloat` methods for `Int` and `String`

---

package-lock.json
packages/safe-ds-lang/src/communication/safe-ds-messaging-provider.ts
packages/safe-ds-lang/src/language/index.ts
packages/safe-ds-lang/src/language/lsp/safe-ds-messaging-provider.ts
packages/safe-ds-lang/src/language/runner/safe-ds-runner.ts
packages/safe-ds-lang/src/language/safe-ds-module.ts
packages/safe-ds-vscode/package.json
packages/safe-ds-vscode/src/extension/commands/installRunner.ts
packages/safe-ds-vscode/src/extension/mainClient.ts

Add a command "Install the Safe-DS Runner" to automatically install the runner and update the settings accordingly. It also gets suggested in the error message if the runner could not be started.

feat: installer for the runner

---

packages/safe-ds-vscode/package.json
packages/safe-ds-vscode/src/extension/mainClient.ts

Remove the "Explore Table" command. This functionality is also available via code lenses, which can be controlled exactly by the language server.

refactor: remove "Explore Table" command

---

packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts
packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts
packages/safe-ds-lang/src/language/validation/types.ts
packages/safe-ds-lang/tests/resources/generation/markdown/annotations/documented/generated/tests/generation/markdown/annotations/documented/MyAnnotation3.md
packages/safe-ds-lang/tests/resources/generation/markdown/annotations/documented/main.sdsstub
packages/safe-ds-lang/tests/resources/generation/markdown/annotations/undocumented/generated/tests/generation/markdown/annotations/undocumented/MyAnnotation3.md
packages/safe-ds-lang/tests/resources/generation/markdown/annotations/undocumented/main.sdsstub
packages/safe-ds-lang/tests/resources/validation/types/checking/arguments/of annotation calls.sdsdev
packages/safe-ds-lang/tests/resources/validation/types/checking/arguments/of calls.sdsdev

Types of arguments of annotation calls are now being checked.

fix: type check arguments of annotation calls

---

packages/safe-ds-lang/src/language/communication/commands.ts
packages/safe-ds-lang/src/language/communication/safe-ds-messaging-provider.ts
packages/safe-ds-lang/src/language/lsp/safe-ds-code-lens-provider.ts
packages/safe-ds-lang/src/language/lsp/safe-ds-execute-command-handler.ts
packages/safe-ds-lang/src/language/runtime/safe-ds-runner.ts
packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts
packages/safe-ds-lang/tests/language/communication/safe-ds-messaging-provider.test.ts
packages/safe-ds-lang/tests/language/lsp/safe-ds-code-lens-provider.test.ts

Closes #1032
Primitive values can now be printed via a code lens.

feat: print values via code lens

---

docs/api/safeds/data/tabular/containers/Column.md
docs/api/safeds/data/tabular/containers/Table.md
docs/api/safeds/data/tabular/containers/TaggedTable.md
docs/api/safeds/data/tabular/containers/TimeSeries.md
docs/api/safeds/lang/Any.md
docs/api/safeds/lang/Float.md
docs/api/safeds/lang/Int.md
docs/api/safeds/lang/List.md
docs/api/safeds/lang/Map.md
docs/api/safeds/lang/String.md
packages/safe-ds-lang/src/language/generation/safe-ds-markdown-generator.ts
packages/safe-ds-lang/tests/resources/generation/markdown/annotations/documented/generated/tests/generation/markdown/annotations/documented/MyAnnotation4.md
packages/safe-ds-lang/tests/resources/generation/markdown/classes/documented/generated/tests/generation/markdown/classes/documented/MyClass6.md
packages/safe-ds-lang/tests/resources/generation/markdown/classes/documented/generated/tests/generation/markdown/classes/documented/MyClass7.md
packages/safe-ds-lang/tests/resources/generation/markdown/enums/documented/generated/tests/generation/markdown/enums/documented/MyEnum2.md
packages/safe-ds-lang/tests/resources/generation/markdown/enums/documented/generated/tests/generation/markdown/enums/documented/MyEnum3.md
packages/safe-ds-lang/tests/resources/generation/markdown/examples/generated/SUMMARY.md
packages/safe-ds-lang/tests/resources/generation/markdown/examples/generated/tests/generation/markdown/examples/MyClass1.md
packages/safe-ds-lang/tests/resources/generation/markdown/examples/generated/tests/generation/markdown/examples/MyClass2.md
packages/safe-ds-lang/tests/resources/generation/markdown/examples/generated/tests/generation/markdown/examples/MyClass3.md
packages/safe-ds-lang/tests/resources/generation/markdown/examples/generated/tests/generation/markdown/examples/MyClass4.md
packages/safe-ds-lang/tests/resources/generation/markdown/examples/generated/tests/generation/markdown/examples/MyClass5.md
packages/safe-ds-lang/tests/resources/generation/markdown/examples/main.sdsstub
packages/safe-ds-lang/tests/resources/generation/markdown/functions/documented/generated/tests/generation/markdown/functions/documented/myFunction5.md
packages/safe-ds-lang/tests/resources/generation/markdown/schemas/documented/generated/tests/generation/markdown/schemas/documented/MySchema3.md
packages/safe-ds-lang/tests/resources/generation/markdown/segments/documented/generated/tests/generation/markdown/segments/documented/mySegment6.md

Lines of an example that likely reference the declaration the example is for are now highlighted.

docs: highlight lines of examples that likely use a declaration

---

packages/safe-ds-lang/src/language/validation/experimentalLanguageFeatures.ts
packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts
packages/safe-ds-lang/tests/resources/validation/experimental language feature/schemas/main.sdsdev

Closes #1078
Schemas are now marked as experimental.

feat: mark schemas as experimental

---

docs/development/testing/generation-testing.md
packages/safe-ds-cli/src/cli/generate.ts
packages/safe-ds-lang/src/language/flow/safe-ds-slicer.ts
packages/safe-ds-lang/src/language/generation/python/safe-ds-python-generator.ts
packages/safe-ds-lang/src/language/purity/model.ts
packages/safe-ds-lang/src/language/runtime/safe-ds-runner.ts
packages/safe-ds-lang/src/language/safe-ds-module.ts
packages/safe-ds-lang/tests/language/flow/safe-ds-slicer.test.ts
packages/safe-ds-lang/tests/language/generation/safe-ds-python-generator/creator.ts
packages/safe-ds-lang/tests/language/generation/safe-ds-python-generator/safe-ds-python-generator.test.ts
packages/safe-ds-lang/tests/resources/generation/python/partial/impure dependency file constant/input.sdsdev
packages/safe-ds-lang/tests/resources/generation/python/partial/impure dependency file parameter/input.sdsdev
packages/safe-ds-lang/tests/resources/generation/python/partial/impure dependency/input.sdsdev
packages/safe-ds-lang/tests/resources/generation/python/partial/pure dependency/input.sdsdev
packages/safe-ds-lang/tests/resources/generation/python/partial/redundant impurity/input.sdsdev
packages/safe-ds-vscode/src/extension/mainClient.ts

Closes partially #1079
Partial code generation now works for multiple targets instead of just one.

feat: partial code generation for multiple targets

---

docs/api/safeds/lang/Any.md
docs/api/safeds/lang/Boolean.md
docs/api/safeds/lang/Float.md
docs/api/safeds/lang/Int.md
docs/api/safeds/lang/List.md
docs/api/safeds/lang/Map.md
docs/api/safeds/lang/Nothing.md
docs/api/safeds/lang/Number.md
docs/api/safeds/lang/String.md
packages/safe-ds-lang/src/resources/builtins/safeds/lang/coreClasses.sdsstub
packages/safe-ds-lang/tests/resources/generation/python/macros/any/generated/tests/generation/python/macros/strings/gen_input.py
packages/safe-ds-lang/tests/resources/generation/python/macros/any/generated/tests/generation/python/macros/strings/gen_input.py.map
packages/safe-ds-lang/tests/resources/generation/python/macros/any/generated/tests/generation/python/macros/strings/gen_input_myPipeline.py
packages/safe-ds-lang/tests/resources/generation/python/macros/any/input.sdsdev

Add a method `toBoolean` to check the truthiness of any value.

feat: Check truthiness of value

---

packages/safe-ds-lang/src/language/validation/other/statements/statements.ts
packages/safe-ds-lang/tests/resources/validation/other/statements/expression statements/has no effect/main.sdsdev

Closes #1142
Suggest adding an assignment if the user likely forgot it.

feat: suggest adding assignment if statement does nothing

---

docs/getting-started/installation.md
packages/safe-ds-vscode/README.md

Add a missing step to the installation tutorial.

docs: add missing step "select location for runner"

---

docs/api/safeds/data/tabular/containers/Cell.md
docs/api/safeds/data/tabular/containers/Column.md
docs/api/safeds/data/tabular/containers/Row.md
docs/api/safeds/data/tabular/containers/Table.md
docs/api/safeds/data/tabular/transformation/TableTransformer.md
docs/api/safeds/ml/classical/classification/Classifier.md
docs/api/safeds/ml/classical/regression/Regressor.md
docs/api/safeds/ml/nn/NeuralNetworkClassifier.md
docs/api/safeds/ml/nn/NeuralNetworkRegressor.md
packages/safe-ds-lang/src/resources/builtins/safeds/data/tabular/containers/Column.sdsstub
packages/safe-ds-lang/src/resources/builtins/safeds/data/tabular/containers/Row.sdsstub
packages/safe-ds-lang/src/resources/builtins/safeds/data/tabular/containers/Table.sdsstub

* Use operators when working with cells in examples
* Regenerate API docs

docs: update API docs

---

packages/safe-ds-cli/README.md

Update the usage information in the CLI README to include all current commands.

docs: update usage info in CLI README
