DSL/com.larsreimann.safeds/build.gradle.kts
* Properly configure dependencies of `sourcesJar` task
* Prevent duplicate entries when creating sources Jar
=> build: fix issues when creating sources Jar

DSL/com.larsreimann.safeds/src/main/kotlin/com/larsreimann/safeds/scoping/SafeDSScopeProvider.kt
Closes #90.
While #90 did not have any effect on the result of the scoping provider, the code was still confusing.  This confusing code is now removed.
=> refactor(scoping): remove outdated code

DSL/com.larsreimann.safeds/build.gradle.kts, DSL/com.larsreimann.safeds/src/main/kotlin/com/larsreimann/safeds/staticAnalysis/schema/SchemaComputer.kt
Closes #82.
Use `kotlinx.dataframe` for inference rather than Tablesaw since it provides a more idiomatic Kotlin API.
=> refactor: replace Tablesaw with kotlinx.dataframe

DSL/com.larsreimann.safeds/src/main/kotlin/com/larsreimann/safeds/constant/SdsFileExtension.kt, DSL/com.larsreimann.safeds/src/main/kotlin/com/larsreimann/safeds/constant/SdsKind.kt, DSL/com.larsreimann.safeds/src/main/kotlin/com/larsreimann/safeds/constant/SdsProtocolQuantifiedTermQuantifier.kt, DSL/com.larsreimann.safeds/src/main/kotlin/com/larsreimann/safeds/constant/SdsProtocolTokenClassValue.kt, DSL/com.larsreimann.safeds/src/main/kotlin/com/larsreimann/safeds/constant/SdsTypeParameterConstraintOperator.kt, DSL/com.larsreimann.safeds/src/main/kotlin/com/larsreimann/safeds/constant/SdsVariance.kt, DSL/com.larsreimann.safeds/src/main/kotlin/com/larsreimann/safeds/emf/Creators.kt, DSL/com.larsreimann.safeds/src/main/kotlin/com/larsreimann/safeds/emf/SimpleShortcuts.kt, DSL/com.larsreimann.safeds/src/main/kotlin/com/larsreimann/safeds/staticAnalysis/schema/SchemaComputer.kt, DSL/com.larsreimann.safeds/src/main/kotlin/com/larsreimann/safeds/utils/MarkerAnnotations.kt, DSL/com.larsreimann.safeds/src/main/kotlin/com/larsreimann/safeds/validation/declarations/ClassChecker.kt, DSL/com.larsreimann.safeds/src/main/kotlin/com/larsreimann/safeds/validation/declarations/CompilationUnitChecker.kt, DSL/com.larsreimann.safeds/src/main/kotlin/com/larsreimann/safeds/validation/declarations/TypeParameterChecker.kt, DSL/com.larsreimann.safeds/src/test/kotlin/com/larsreimann/safeds/emf/CreatorsTest.kt, DSL/com.larsreimann.safeds/src/test/kotlin/com/larsreimann/safeds/staticAnalysis/linking/TypeArgumentToTypeParameterTest.kt, DSL/com.larsreimann.safeds/src/test/kotlin/com/larsreimann/safeds/staticAnalysis/schema/InitialSchemaInferenceTest.kt, DSL/com.larsreimann.safeds/src/testFixtures/kotlin/com/larsreimann/safeds/testing/TestResourceUtils.kt, docs/Development/how-to-add-a-new-language-concept.md
Particularly the creators are also of interest for the https://github.com/lars-reimann/api-editor. Their interface should be stable and experimental parts should be highlighted as such. This is now possible with the annotation `@ExperimentalSdsApi`. I've retroactively added this annotations to appropriate declarations.
In the future this annotation should be added to all new
* constants (`constant/**`)
* creators (`emf/Creators.kt`)
* shortcuts (`emf/SimpleShortcuts.kt`)
* static analyses (`staticAnalysis/**`)
=> refactor!: annotation to mark API elements as experimental

Runtime/safe-ds/safe_ds/data/_table.py, Runtime/safe-ds/tests/data/_table/test_sort_columns.py
- Lambda now uses integer for comparision
- sort is now used for comparision (better than O(n²)
- __eq__ now caches tables and avoids sorting them twice
=> perf: More efficient table sorting + more efficient comparison + correct lambda

Runtime/safe-ds/safe_ds/data/_table.py, Runtime/safe-ds/tests/data/_table/test_sort_columns.py
Closes #305 .
Added method sort_columns in Table and changed equals to not care about order of columns. The sort_columns method by default sorts after alphabetically order which can be changed by porividing a lambda-function as parameter.
=> feat: Added method sort_columns in Table and changed equals to not care about order

.github/dependabot.yml, README.md, docs/Stdlib/python/column.md, docs/Stdlib/python/row.md, docs/Stdlib/python/table.md, docs/requirements.txt, mkdocs.yml, readthedocs.yml
Closes #315.
Upload our existing documentation and some auto-generate documentation about the Python library to [readthedocs.org](https://readthedocs.org). We can later enhance the documentation, this PR just establishes the necessary infrastructure.
=> docs: upload documentation to readthedocs.org

.editorconfig, DSL/com.larsreimann.safeds/src/main/kotlin/com/larsreimann/safeds/stdlibDocumentation/DocumentationGenerator.kt, docs/DSL/README.md, docs/DSL/common/imports.md, docs/DSL/common/packages.md, docs/DSL/common/parameters.md, docs/DSL/common/results.md, docs/DSL/common/types.md, docs/DSL/common/variance.md, docs/DSL/stub-language/annotations.md, docs/DSL/stub-language/enumerations.md, docs/DSL/stub-language/global-functions.md, docs/DSL/workflow-language/expressions.md, docs/DSL/workflow-language/statements.md, docs/DSL/workflow-language/steps.md, docs/DSL/workflow-language/workflows.md, docs/Development/how-to-add-a-new-language-concept.md, docs/Development/how-to-prepare-a-release.md, docs/Stdlib/API/safeds_lang.md
* Put a blank line before lists so they get rendered properly
* Use full GitHub URLs to point to files outside the documentation to fix broken links
* Downside: We now always point to the main branch
* Remove custom table of contents in auto-generated documentation for the DSL standard library
=> docs: fix various issues wrt. mkdocs and readthedocs

Runtime/safe-ds/safe_ds/data/_table.py, Runtime/safe-ds/tests/data/_table/test_remove_outliers.py
Closes #356.
The table schema is kept when removing_outliers.
```
table = # define Table()
names = table.get_column_names()
table = table.remove_outliers()
assert names = table.get_column_names() # now returns as true
```
=> fix: Table method remove_outliers() removes column names

docs/DSL/README.md, docs/DSL/pipeline-language/README.md, docs/DSL/pipeline-language/steps.md
Replace the term "Machine Learning" with "data science" in the language documentation.
=> docs: replace "Machine Learning" with data science

.github/workflows/pr.yml
Running only the tests of changed components leads to incorrect coverage reports and prevents us from making the tests required. The latter allows PR with failing tests to be merged, like #391.
=> ci: always run all tests

Runtime/safe-ds/safeds/data/tabular/_column.py, Runtime/safe-ds/safeds/data/tabular/transformation/_imputer.py, Runtime/safe-ds/tests/data/tabular/_column/test_mode.py, Runtime/safe-ds/tests/data/tabular/_table/test_summary.py, Runtime/safe-ds/tests/data/tabular/transformation/_imputer/test_imputer.py
Closes #395 .
now mode returns a list of the most common elements
changed in imputer that the first element of the list is taken but maybe we want to change this
adjusted tests and fixed test_summary
=> fix: now mode returns a list

Runtime/safe-ds/safeds/data/tabular/_table.py, Runtime/safe-ds/safeds/exceptions/__init__.py, Runtime/safe-ds/safeds/exceptions/_data_exceptions.py, Runtime/safe-ds/tests/data/tabular/_column/test_from_columns.py, Runtime/safe-ds/tests/data/tabular/_row/test_from_rows.py, docs/Stdlib/python/Tutorials/data_processing.md
Related to Issue #380 
Added a new data processing tutorial
`from_rows` and `from_columns` now raise a `MissingDataError` if the provided lists of rows/columns are empty
if none of the rows of a table in `filter_rows` match with the query the function now returns an empty table with the same schema as the original table
=> feat: Added MissingDataError + Data processing tutorial

.github/dependabot.yml
* Let Dependabot keep the Langium component up-to-date
=> ci: configure Dependabot for the Langium component

Runner/.coveragerc
`TYPE_CHECKING` blocks are supposed to be never executed, so they can also never be covered by tests. Now they are also no longer included in the test coverage.
=> test: ignore `TYPE_CHECKING` blocks when computing coverage

.github/workflows/main.yml, .github/workflows/pr.yml, DSL/package-lock.json, DSL/package.json, DSL/vitest.config.ts
If the `clover.xml` report is sent to Codecov lines with conditionals are incorrectly marked as only partially covered (see [this issue](https://github.com/istanbuljs/istanbuljs/issues/695)). We are now send the JSON report instead to get a more accurate picture of the code coverage.
=> ci: send JSON report to Codecov

src/language/validation/other/declarations/typeParameterConstraints.ts, src/language/validation/safe-ds-validator.ts, tests/resources/validation/other/declarations/type parameter constraints/left operand must be own type parameter/main.sdstest
Closes #562
Show an error if the left operand of a type parameter constraint refers to a type parameter that does not belong to the declaration with the constraint (but a declaration that contains it).
=> feat: error if left operand of type parameter constraint does not belong to declaration with constraint

src/language/grammar/safe-ds.langium, src/language/validation/other/declarations/parameterLists.ts, src/language/validation/safe-ds-validator.ts, tests/resources/validation/other/declarations/parameter lists/must not have required after optional/main.sdstest, tests/resources/validation/other/declarations/parameter lists/must not mix optional and variadic/main.sdstest, tests/resources/validation/other/declarations/parameter lists/variadic must be last/main.sdstest
Closes partially #543.
Show an error if a parameter list:
* has more parameters after a variadic one,
* has optional parameters and a variadic one, or
* has required parameters after optional ones.
=> feat: port validation of parameter lists

src/language/grammar/safe-ds.langium, src/language/validation/other/argumentLists.ts, src/language/validation/other/declarations/parameterLists.ts, src/language/validation/other/declarations/parameters.ts, src/language/validation/other/imports.ts, src/language/validation/other/types/callableTypes.ts, src/language/validation/other/types/typeArgumentLists.ts, src/language/validation/other/types/unionTypes.ts, src/language/validation/safe-ds-validator.ts, src/language/validation/value.ts, tests/language/validation/testValidation.test.ts, tests/resources/grammar/expressions/calls/good-named type argument with test markers.sdstest, tests/resources/grammar/expressions/calls/good-positional type argument with tests markers.sdstest, tests/resources/validation/other/argument lists/must not have positional argument after named argument/main.sdstest, tests/resources/validation/other/declarations/parameter lists/must not mix optional and variadic/main.sdstest, tests/resources/validation/other/declarations/parameter/variadic must not be optional/main.sdstest, tests/resources/validation/other/types/callable types/must not have optional parameters/optional.sdstest, tests/resources/validation/other/types/callable types/must not have optional parameters/required.sdstest, tests/resources/validation/other/types/callable types/must not have optional parameters/variadic optional.sdstest, tests/resources/validation/other/types/callable types/must not have optional parameters/variadic required.sdstest, tests/resources/validation/other/types/type argument lists/must not have positional type argument after named type argument/main.sdstest, tests/resources/validation/other/types/union types/must have type arguments/main.sdstest
Show an error if:
* A union type has no type arguments
* A callable type has optional parameters
* Positional type arguments occur after named type arguments
* Positional arguments occur after named arguments
* A parameter is variadic and optional
=> feat: port additional validation checks to `Langium

src/language/validation/names.ts, tests/resources/validation/names/duplicates/in class/main.sdstest
Classes can now have static and instance members with the same name. This better matches the behavior of the scoping mechanism that does not resolve static references to instance members or dynamic references to static members.
=> feat: allow instance and static members of classes to have the same name

src/language/scoping/safe-ds-scope-computation.ts, tests/resources/scoping/named types/to containing named type declaration/main.sdstest
Closes #29
Closes partially #540
Test that containing classes can be referenced from the parent type list.
=> test: reference containing class from parent type list

src/language/scoping/safe-ds-scope-computation.ts, src/language/scoping/safe-ds-scope-provider.ts, tests/resources/scoping/named types/to enum variant in global enum/main.sdstest, tests/resources/scoping/named types/to enum variant in nested enum/main.sdstest, tests/resources/scoping/type arguments/to something other than type parameter/main.sdstest, tests/resources/scoping/type arguments/to type parameter in containing named type declaration/main.sdstest, tests/resources/scoping/type arguments/to type parameter in enum variant in global enum/main.sdstest, tests/resources/scoping/type arguments/to type parameter in enum variant in nested enum/main.sdstest, tests/resources/scoping/type arguments/to type parameter in global class/main.sdstest, tests/resources/scoping/type arguments/to type parameter in nested class/main.sdstest, tests/resources/scoping/type arguments/to unresolved/main.sdstest
Closes partially #540
Implement scoping rules for the `typeParameter` property of a type argument.
=> feat: scoping for type arguments

docs/language/common/types.md, docs/language/common/variance.md, src/language/formatting/safe-ds-formatter.ts, src/language/grammar/safe-ds.langium, tests/resources/formatting/types/named types/type argument and nullable.sdstest, tests/resources/formatting/types/named types/type arguments and not nullable.sdstest, tests/resources/grammar/types/named types/good-type argument and nullable.sdstest, tests/resources/grammar/types/named types/good-type arguments and not nullable.sdstest
There is currently no use-case for star projections and use-site variance, so they are not worth the effort to implement. Moreover, these concepts are difficult to explain.
=> feat: remove star projection and use-site variance

src/language/scoping/safe-ds-scope-provider.ts, tests/resources/scoping/annotation calls/across files/main with qualified import.sdstest, tests/resources/scoping/annotation calls/across files/resource other package.sdstest, tests/resources/scoping/named types/across files/to global classes/main with qualified import.sdstest, tests/resources/scoping/named types/across files/to global classes/resource other package.sdstest, tests/resources/scoping/named types/across files/to global enums/main with qualified import.sdstest, tests/resources/scoping/named types/across files/to global enums/resource other package.sdstest
References to declarations of the wrong node type were incorrectly resolved if they were imported in a qualified import. This PR adds tests to reproduce the bug and the missing check of the node type.
=> fix: resolution of references to declarations of wrong node type

src/language/scoping/safe-ds-scope-provider.ts, src/language/typing/model.ts, src/language/typing/safe-ds-type-computer.ts, tests/resources/scoping/arguments/of annotation calls/main.sdstest, tests/resources/scoping/arguments/of annotation calls/to parameter/main.sdstest, tests/resources/scoping/arguments/of annotation calls/to something other than parameter/main.sdstest, tests/resources/scoping/arguments/of annotation calls/unresolved/main.sdstest, tests/resources/scoping/arguments/of calls/to parameter of annotation/main.sdstest, tests/resources/scoping/arguments/of calls/to parameter of block lambda/main.sdstest, tests/resources/scoping/arguments/of calls/to parameter of callable type/main.sdstest, tests/resources/scoping/arguments/of calls/to parameter of class/main.sdstest, tests/resources/scoping/arguments/of calls/to parameter of enum variant/main.sdstest, tests/resources/scoping/arguments/of calls/to parameter of expression lambda/main.sdstest, tests/resources/scoping/arguments/of calls/to parameter of function/main.sdstest, tests/resources/scoping/arguments/of calls/to parameter of segment/main.sdstest, tests/resources/scoping/arguments/of calls/to something other than parameter/main.sdstest, tests/resources/scoping/arguments/of calls/unresolved/main.sdstest
Closes partially #540.
Named arguments now correctly point to their corresponding parameter.
=> feat: scoping of arguments

src/language/helpers/checks.ts, src/language/helpers/safe-ds-node-mapper.ts, src/language/helpers/shortcuts.ts, src/language/partialEvaluation/toConstantExpressionOrUndefined.ts, src/language/safe-ds-module.ts, src/language/scoping/safe-ds-scope-provider.ts, src/language/typing/safe-ds-type-computer.ts, src/language/validation/names.ts, src/language/validation/other/types/callableTypes.ts, src/language/workspace/safe-ds-package-manager.ts, tests/helpers/__snapshots__/location.test.ts.snap, tests/helpers/__snapshots__/nodeFinder.test.ts.snap, tests/helpers/location.test.ts, tests/helpers/location.ts, tests/helpers/nodeFinder.test.ts, tests/helpers/nodeFinder.ts, tests/language/helpers/safe-ds-node-mapper/argumentToParameterOrUndefined.test.ts, tests/language/helpers/safe-ds-node-mapper/callToCallableOrNull.test.ts, tests/language/helpers/safe-ds-node-mapper/callToCallableOrUndefined.test.ts, tests/language/helpers/safe-ds-node-mapper/typeArgumentToTypeParameterOrUndefined.test.ts, tests/language/partialEvaluation/testPartialEvaluation.test.ts, tests/language/typing/testTyping.test.ts
Add a service that can map
* arguments to parameters,
* type arguments to type parameters,
* calls to callables.
=> feat: node mapper

src/language/helpers/safe-ds-node-mapper.ts, src/language/typing/safe-ds-type-computer.ts, tests/resources/typing/declarations/parameters/of block lambdas/that are isolated/main.sdstest, tests/resources/typing/declarations/parameters/of block lambdas/that are passed as arguments/main.sdstest, tests/resources/typing/declarations/parameters/of block lambdas/that are yielded/main.sdstest, tests/resources/typing/declarations/parameters/of block lambdas/with manifest types/main.sdstest, tests/resources/typing/declarations/parameters/of expression lambdas/that are isolated.sdstest, tests/resources/typing/declarations/parameters/of expression lambdas/that are isolated/main.sdstest, tests/resources/typing/declarations/parameters/of expression lambdas/that are passed as arguments/main.sdstest, tests/resources/typing/declarations/parameters/of expression lambdas/that are yielded/main.sdstest, tests/resources/typing/declarations/parameters/of expression lambdas/with manifest types/main.sdstest, tests/resources/typing/expressions/block lambdas/that are isolated/main.sdstest, tests/resources/typing/expressions/block lambdas/that are passed as arguments/main.sdstest, tests/resources/typing/expressions/block lambdas/that are yielded/main.sdstest, tests/resources/typing/expressions/block lambdas/with manifest types/main.sdstest, tests/resources/typing/expressions/expression lambdas/that are isolated/main.sdstest, tests/resources/typing/expressions/expression lambdas/that are passed as arguments/main.sdstest, tests/resources/typing/expressions/expression lambdas/that are yielded/main.sdstest, tests/resources/typing/expressions/expression lambdas/with manifest types/main.sdstest
Closes partially #541
* Compute the type of parameters of lambdas that are passed as arguments.
* Compute the type of lambdas that are passed as arguments.
=> feat: compute types of lambdas that are passed as arguments

src/language/workspace/safe-ds-package-manager.ts, tests/helpers/diagnostics.ts, tests/language/formatting/creator.ts, tests/language/helpers/safe-ds-node-mapper/assigneeToAssignedObjectOrUndefined.test.ts, tests/language/partialEvaluation/creator.ts, tests/language/scoping/creator.ts, tests/language/typing/creator.ts, tests/language/validation/creator.ts, tests/resources/validation/other/modules/must state package/stub file (only imports).sdsstub
The previous way to check for syntax errors in test resources did not fully take the semantics of promises into account. Thus, it could sometimes happen that syntax errors were missed. This PR rectifies this. As a side effect, the warnings `Attempted reference resolution before document reached ComputedScopes state` are gone too.
=> test: properly check for syntax errors in test files

tests/helpers/testChecks.test.ts, tests/helpers/testChecks.ts, tests/helpers/testResources.test.ts, tests/helpers/testResources.ts, tests/language/formatting/creator.ts, tests/language/generation/creator.ts, tests/language/generation/testGeneration.test.ts, tests/language/grammar/creator.ts, tests/language/partialEvaluation/creator.ts, tests/language/partialEvaluation/testPartialEvaluation.test.ts, tests/language/scoping/creator.ts, tests/language/scoping/testScoping.test.ts, tests/language/typing/creator.ts, tests/language/typing/testTyping.test.ts, tests/language/validation/creator.ts, tests/language/validation/testValidation.test.ts
It's difficult to work with arbitrary paths, since they might be relative to some other directory or absolute. This led to long variable names to precisely express what a path meant. This PR instead refactors the test creators and some helpers to provide URI objects instead.
=> refactor: use URIs instead of paths (strings) in tests

src/language/helpers/safe-ds-node-mapper.ts, src/language/validation/other/declarations/parameters.ts, src/language/validation/other/declarations/placeholders.ts, src/language/validation/safe-ds-validator.ts, tests/language/helpers/safe-ds-node-mapper/parameterToReferences.test.ts, tests/language/helpers/safe-ds-node-mapper/placeholdersToReferences.test.ts, tests/language/helpers/safe-ds-node-mapper/resultToYields.test.ts, tests/resources/validation/other/declarations/parameter/unused/main.sdstest, tests/resources/validation/other/declarations/placeholder/unused/main.sdstest
Show a warning if a parameter or placeholder is unused and suggest removing it.
=> feat: warn if parameters or placeholders are unused

src/language/grammar/safe-ds-value-converter.ts, tests/helpers/nodeFinder.test.ts, tests/helpers/nodeFinder.ts, tests/language/grammar/safe-ds-value-converter.test.ts, tests/resources/validation/names/casing/annotations.sdstest, tests/resources/validation/names/casing/attributes.sdstest, tests/resources/validation/names/casing/block lambda results.sdstest, tests/resources/validation/names/casing/classes.sdstest, tests/resources/validation/names/casing/enum variants.sdstest, tests/resources/validation/names/casing/enums.sdstest, tests/resources/validation/names/casing/functions.sdstest, tests/resources/validation/names/casing/package name lowercase escaped.sdstest, tests/resources/validation/names/casing/parameters.sdstest, tests/resources/validation/names/casing/pipelines.sdstest, tests/resources/validation/names/casing/placeholders.sdstest, tests/resources/validation/names/casing/results.sdstest, tests/resources/validation/names/casing/schemas.sdstest, tests/resources/validation/names/casing/segments.sdstest, tests/resources/validation/names/casing/type parameters.sdstest, vitest.config.ts
Closes #579
Backticks allow using keywords as IDs. This now removes them properly from IDs.
=> feat: handle backticks surrounding IDs

.gitignore, langium-config.json, syntaxes/safe-ds.tmLanguage.json
Various improvements to the auto-generated TextMate grammar:
* Categorization of keywords into correct groups
* Description of number literals
* Treatment of keywords that are enclosed in backticks as names
* Test markers are no longer treated as comments
=> feat: improved TextMate grammar

src/language/validation/experimentalLanguageFeature.ts, src/language/validation/safe-ds-validator.ts, src/resources/builtins/safeds/lang/coreAnnotations.sdsstub, src/resources/builtins/safeds/lang/documentation.sdsstub, tests/resources/validation/experimental language feature/indexed access/main.sdstest
Closes #108
Warn if experimental language features are used. For the moment, this is only indexed accesses.
=> feat: warn if experimental language features are used

src/language/scoping/safe-ds-scope-provider.ts, src/language/validation/other/expressions/memberAccesses.ts, src/language/validation/safe-ds-validator.ts, tests/resources/scoping/member accesses/to class members/instance attributes/main.sdstest, tests/resources/scoping/member accesses/to class members/instance methods/main.sdstest, tests/resources/validation/other/expressions/member accesses/missing safe access/main.sdstest, tests/resources/validation/style/unnecessary safe access/main.sdstest
* If a member access is not null safe, but the receiver is nullable, an error is shown now.
* The scope provider is now more relaxed and points to the correct class members, even if the member access is missing null safety.
=> feat: error if member access must be null safe but isn't

src/language/validation/other/imports.ts, src/language/validation/other/modules.ts, src/language/validation/safe-ds-validator.ts, tests/resources/validation/other/imports/empty.sdstest, tests/resources/validation/other/imports/main with issues.sdstest, tests/resources/validation/other/imports/main without issues.sdstest, tests/resources/validation/other/imports/non empty.sdstest
* Show an error if a package is imported that does not exist
* Show a warning if an empty package is imported
=> feat: validate package of imports

src/language/validation/other/expressions/references.ts, src/language/validation/safe-ds-validator.ts, tests/resources/validation/other/expressions/references/function pointer/main.sdstest
Closes #565
To provide a cleaner graphical view, this PR makes the use of function pointers (to functions/segments) an error. Lambdas can be used instead.
=> feat: error if function pointers are used

src/language/builtins/safe-ds-annotations.ts, src/language/validation/builtins/repeatable.ts, src/language/validation/safe-ds-validator.ts, tests/resources/validation/builtins/annotations/repeatable/main.sdstest, tests/resources/validation/other/statements/assignments/nothing assigned/main.sdstest
Show an error if annotation that is not repeatable (default, unless it has the `@Repeatable` annotation) is repeated.
=> feat: error if single use annotations are used multiple times

src/language/helpers/safe-ds-node-mapper.ts, src/language/scoping/safe-ds-scope-provider.ts, src/language/typing/model.ts, src/language/typing/safe-ds-class-hierarchy.ts, src/language/typing/safe-ds-type-computer.ts, src/language/validation/other/declarations/annotationCalls.ts, src/language/validation/other/expressions/memberAccesses.ts, src/language/validation/safe-ds-validator.ts, tests/language/helpers/safe-ds-node-mapper/callToCallableOrUndefined.test.ts, tests/resources/typing/expressions/calls/of enum variants/main.sdstest, tests/resources/typing/expressions/member accesses/to enum variants/main.sdstest, tests/resources/validation/other/declarations/annotation calls/missing argument list/main.sdstest, tests/resources/validation/other/expressions/member accesses/enum variant must be instantiated/main.sdstest
Show an error if
* an annotation call is missing an argument list,
* a reference to an enum variant is missing an argument list.
=> feat: error if argument lists are missing

src/language/typing/safe-ds-type-computer.ts, src/language/validation/other/expressions/references.ts, src/language/validation/safe-ds-validator.ts, tests/resources/typing/expressions/member accesses/to other/main.sdstest, tests/resources/validation/other/expressions/references/static class reference/main.sdstest, tests/resources/validation/other/expressions/references/static enum reference/main.sdstest
Show an error if a class or enum is statically referenced. They must only be referenced to access one of their members/variants or to call them¹.
-----
¹ If they are not callable, we already show another error.
=> feat: error if class or enum are statically referenced

src/language/grammar/safe-ds.langium, src/language/scoping/safe-ds-scope-provider.ts, src/language/validation/other/expressions/lambdas.ts, src/language/validation/other/expressions/memberAccesses.ts, src/language/validation/safe-ds-validator.ts, src/language/validation/types.ts, tests/resources/validation/other/expressions/lambdas/context/assigned to typed parameter.sdstest, tests/resources/validation/other/expressions/lambdas/context/assigned to unresolved parameter.sdstest, tests/resources/validation/other/expressions/lambdas/context/assigned to untyped parameter.sdstest, tests/resources/validation/other/expressions/lambdas/context/invalid context.sdstest
Closes #409
Show an error if a lambda is used in the wrong context. They must be assigned to a type parameter, either as its default value or an argument.
=> feat: error if lambda is used in wrong context

esbuild.mjs, src/language/helpers/nodeProperties.ts, src/language/validation/builtins/repeatable.ts, src/language/validation/other/argumentLists.ts, src/language/validation/safe-ds-validator.ts, src/language/validation/types.ts, tests/resources/validation/builtins/annotations/repeatable/main.sdstest, tests/resources/validation/other/argument lists/duplicate parameter/main.sdstest, tests/resources/validation/other/argument lists/missing required parameter/main.sdstest, tests/resources/validation/other/argument lists/too many arguments/main.sdstest, tests/resources/validation/types/checking/receiver of call must be callable/main.sdstest, tests/resources/validation/types/named types/missing type parameter/main.sdstest
Show an error if an argument list of an annotation call or a call
* does not set required parameters,
* sets a parameter multiple times,
* passes too many arguments.
=> feat: various checks for argument lists

src/language/validation/other/argumentLists.ts, tests/resources/validation/other/argument lists/missing required parameter/dont show this error if the argument list is missing altogether.sdstest
If an annotation call had no argument list and did not set some required parameters, two separate errors were shown in the same place. This PR hides one of them.
=> fix: duplicate error if annotation call has no argument list and lacks required parameters

.github/linters/.ruff.toml, docs/development/formatting-testing.md, docs/language/common/comments.md, docs/language/common/imports.md, docs/language/common/packages.md, docs/language/common/parameters.md, docs/language/common/results.md, docs/language/common/types.md, docs/language/common/variance.md, docs/language/pipeline-language/expressions.md, docs/language/pipeline-language/pipelines.md, docs/language/pipeline-language/segments.md, docs/language/pipeline-language/statements.md, docs/language/stub-language/annotations.md, docs/language/stub-language/classes.md, docs/language/stub-language/enumerations.md, docs/language/stub-language/global-functions.md, docs/lexer/pyproject.toml, docs/lexer/safe_ds_lexer/__init__.py, docs/lexer/safe_ds_lexer/_safe_ds_lexer.py, docs/requirements.txt, mkdocs.yml
Closes #439
Add syntax highlighting for Safe-DS code in the generated documentation.
=> docs: syntax highlighting in documentation

docs/language/pipeline-language/expressions.md, esbuild.mjs, language-configuration.json, src/language/grammar/safe-ds-value-converter.ts, src/language/grammar/safe-ds.langium, src/language/partialEvaluation/safe-ds-partial-evaluator.ts, src/language/validation/other/expressions/infixOperations.ts, syntaxes/safe-ds.tmLanguage.json, tests/language/grammar/safe-ds-value-converter.test.ts, tsconfig.json
Add conversion for ints and strings, including proper handling of escape sequences.
=> feat: value converter for strings & ints

src/language/validation/experimentalLanguageFeatures.ts, src/language/validation/safe-ds-validator.ts, tests/resources/scoping/member accesses/skip-main.sdstest, tests/resources/validation/experimental language feature/maps/main.sdstest
Our map literals are fairly new and need to be tested for some time. Because of this, they are now marked as experimental.
=> fix: mark map literals as experimental

src/language/helpers/safe-ds-node-mapper.ts, src/language/safe-ds-module.ts, src/language/typing/safe-ds-class-hierarchy.ts, src/language/workspace/safe-ds-document-builder.ts, tests/language/builtins/builtinFilesCorrectness.test.ts
Linking or custom validation errors are no longer displayed if a document has lexing or parsing errors. This better highlights the criticality of those issues and ensures that users fix those first. It also prevents the display of some additional errors that were caused by the lexing or parsing errors.
=> feat: stop validation after lexing/parsing errors

src/language/validation/other/modules.ts, src/language/validation/safe-ds-validator.ts, tests/resources/validation/other/modules/pipeline files must not be in safeds package/pipe elsewhere.sdspipe, tests/resources/validation/other/modules/pipeline files must not be in safeds package/pipe in safeds.sdspipe, tests/resources/validation/other/modules/pipeline files must not be in safeds package/pipe in subpackage of safeds.sdspipe, tests/resources/validation/other/modules/pipeline files must not be in safeds package/stub elsewhere.sdsstub, tests/resources/validation/other/modules/pipeline files must not be in safeds package/stub in safeds.sdsstub, tests/resources/validation/other/modules/pipeline files must not be in safeds package/stub in subpackage of safeds.sdsstub, tests/resources/validation/other/modules/pipeline files must not be in safeds package/test elsewhere.sdstest, tests/resources/validation/other/modules/pipeline files must not be in safeds package/test in safeds.sdstest, tests/resources/validation/other/modules/pipeline files must not be in safeds package/test in subpackage of safeds.sdstest
Closes #671
Show an error if a pipeline file is in a `safeds.xy` package.
=> feat: error if pipeline file is in a `safeds.xy` package

src/language/validation/experimentalLanguageFeatures.ts, src/language/validation/safe-ds-validator.ts, tests/resources/validation/experimental language feature/union types/main.sdstest
Closes #674
Using a union type now shows a warning that this language feature is experimental.
=> feat: mark union types as experimental

src/language/validation/experimentalLanguageFeatures.ts, src/language/validation/names.ts, src/language/validation/other/types/unionTypes.ts, src/language/validation/safe-ds-validator.ts, tests/resources/validation/experimental language feature/indexed access/main.sdstest, tests/resources/validation/experimental language feature/maps/main.sdstest, tests/resources/validation/experimental language feature/union types/main.sdstest, tests/resources/validation/other/types/union types/context/main.sdstest, tests/resources/validation/other/types/union types/context/nested.sdstest, tests/resources/validation/other/types/union types/duplicate types/empty list.sdstest, tests/resources/validation/other/types/union types/duplicate types/main.sdstest, tests/resources/validation/other/types/union types/must have types/main.sdstest
Closes #675
Union types are now only allowed as parameters of annotations, classes, and functions. This way, no values with a union type appear inside pipelines or segments.
=> feat: check context of union types

src/language/builtins/packageNames.ts, src/language/lsp/safe-ds-node-kind-provider.ts, src/language/lsp/safe-ds-semantic-token-provider.ts, src/language/validation/names.ts, src/language/validation/other/modules.ts, tests/language/lsp/safe-ds-document-symbol-provider.test.ts, tests/language/lsp/safe-ds-semantic-token-provider.test.ts, tests/resources/validation/names/duplicates/across files/other package.sdstest, tests/resources/validation/names/duplicates/across files/safeds 1.sdstest, tests/resources/validation/names/duplicates/across files/safeds 2.sdstest, tests/resources/validation/names/duplicates/across files/safeds.sdstest, tests/resources/validation/names/duplicates/across files/same package.sdstest
Closes #672
Show an error if the simple names of builtin declarations collide. For other packages, only the qualified names of declarations must be unique.
=> feat: error if simple names of builtin declarations collide

src/language/helpers/nodeProperties.ts, src/language/lsp/safe-ds-inlay-hint-provider.ts, src/language/safe-ds-module.ts, tests/language/lsp/safe-ds-inlay-hint-provider.test.ts
Closes #679
Show inlay hints for
* the type of block lambda results, placeholders, yields,
* the corresponding parameter for positional arguments.
=> feat: inlay hint provider

src/cli/generator.ts, src/language/builtins/safe-ds-annotations.ts, src/language/validation/names.ts, src/resources/builtins/safeds/lang/codeGeneration.sdsstub, tests/resources/generation/expressions/call/input.sdstest, tests/resources/generation/expressions/call/output/tests/generator/call/gen_input.py, tests/resources/generation/expressions/member access/input.sdstest, tests/resources/generation/expressions/member access/output/tests/generator/memberAccess/gen_input.py
Closes #617 
- added `PythonCall` annotation to builtins
- added code generation for direct function calls and member access function calls
- added tests
=> feat: PythonCall annotation

src/language/validation/builtins/pythonModule.ts, src/language/validation/builtins/pythonName.ts, src/language/validation/safe-ds-validator.ts, tests/resources/validation/builtins/annotations/pythonModule/error.sdstest, tests/resources/validation/builtins/annotations/pythonModule/no error.sdstest, tests/resources/validation/builtins/annotations/pythonName/identical to safe-ds name/main.sdstest, tests/resources/validation/builtins/annotations/pythonName/identical to safe-ds name/no annotation.sdstest, tests/resources/validation/builtins/annotations/pythonName/mutually exclusive with python call/main.sdstest
`@PythonCall` is a more general version of `@PythonName`. If `@PythonCall` is set, `@PythonName` gets ignored completely. We now show an error if both annotation are used together on a function.
=> feat: error if @PythonName and @PythonCall are set on a function

src/language/validation/builtins/pythonCall.ts, src/language/validation/safe-ds-validator.ts, tests/resources/validation/builtins/annotations/pythonCall/main.sdstest
Show an error if the call specification inside a `@PythonCall` cannot be interpreted.
=> feat: check template expressions inside `@PythonCall`

src/language/documentation/safe-ds-documentation-provider.ts, src/language/safe-ds-module.ts, src/resources/builtins/safeds/lang/codeGeneration.sdsstub, tests/language/documentation/safe-ds-documentation-provider.test.ts
Closes partially #669
Add a custom documentation provider. It can now handle tags `@param`, `@result`, and `@typeParam` to set the documentation for parameters, results, and type parameters of a callable respectively.
=> feat: documentation provider

src/language/lsp/safe-ds-semantic-token-provider.ts, syntaxes/safe-ds.tmLanguage.json, tests/language/lsp/safe-ds-semantic-token-provider.test.ts
Closes partially #669
Highlight tags in documentation comments:
=> feat: syntax highlighting in documentation comments

packages/safe-ds-cli/esbuild.mjs, packages/safe-ds-cli/src/generate.ts, packages/safe-ds-cli/src/main.ts, packages/safe-ds-cli/tests/main.test.ts, packages/safe-ds-vscode/tests/helpers/testResources.ts
Where possible, replace `__dirname` (which does not work in modules) with `meta.import.url`, which does. Once VS Code can handle ESM, we can set the output format to "ESM" in the ESBuild configs.
See also:
* [Node.js Docs](https://nodejs.org/dist/latest/docs/api/esm.html#esm_no_filename_or_dirname)
* [StackOverflow](https://stackoverflow.com/questions/46745014/alternative-for-dirname-in-node-js-when-using-es6-modules)
=> refactor: remove references to `__dirname` where possible

docs/language/common/imports.md, docs/language/common/packages.md, docs/language/common/parameters.md, docs/language/pipeline-language/segments.md, docs/language/stub-language/annotations.md
Use titles for code blocks to differentiate whether they denote Python code or Safe-DS code. Remove the old comments inside the code blocks that expressed the same thing.
=> docs: use titles for code blocks

.github/workflows/release.yml, package-lock.json, packages/safe-ds-cli/README.md, packages/safe-ds-cli/esbuild.mjs, packages/safe-ds-cli/package.json, packages/safe-ds-cli/src/generate.ts, packages/safe-ds-vscode/src/language/generation/safe-ds-python-generator.ts, packages/safe-ds-vscode/tests/language/generation/testGeneration.test.ts
Fixes various issues with the CLI. A first version is now available on NPM.
=> fix: setup of CLI

packages/safe-ds-lang/src/language/main.ts, packages/safe-ds-lang/src/language/partialEvaluation/model.ts, packages/safe-ds-lang/src/language/typing/model.ts, packages/safe-ds-lang/src/language/typing/safe-ds-core-types.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/tests/language/partialEvaluation/creator.ts, packages/safe-ds-lang/tests/language/partialEvaluation/model.test.ts, packages/safe-ds-lang/tests/language/partialEvaluation/testPartialEvaluation.test.ts
Add missing tests for the model classes of the partial evaluator.
=> test: model classes of partial evaluator

packages/safe-ds-lang/src/language/scoping/safe-ds-scope-provider.ts, packages/safe-ds-lang/tests/resources/scoping/references/in same file/to containing declarations/main.sdstest
Closes #540
Implement the same scoping rules for references to containing declarations as for named types.
=> feat: scoping for references to containing declarations

packages/safe-ds-lang/tests/resources/validation/other/declarations/segments/unused/main.sdstest, packages/safe-ds-lang/tests/resources/validation/other/declarations/segments/unused/same package.sdstest
Add a missing test to ensure that public segments are never marked as unused.
=> test: public segments are never marked as unused

packages/safe-ds-lang/src/language/lsp/safe-ds-inlay-hint-provider.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-inlay-hint-provider.test.ts
Show tooltips on inlay code hints:
* For the corresponding parameter, its documentation is displayed.
* For named types, the documentation of the corresponding declaration is used.
=> feat: tooltips for inlay hints

packages/safe-ds-lang/src/language/helpers/nodeProperties.ts, packages/safe-ds-lang/src/language/typing/model.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/tests/language/typing/safe-ds-type-checker.test.ts
Closes partially #666
Implement & test type checker services. A later PR will use the service to implement validation for types.
=> feat: type checker service

packages/safe-ds-lang/src/language/documentation/safe-ds-comment-provider.ts, packages/safe-ds-lang/src/language/generation/safe-ds-python-generator.ts, packages/safe-ds-lang/src/language/helpers/safe-ds-node-mapper.ts, packages/safe-ds-lang/src/language/lsp/safe-ds-formatter.ts, packages/safe-ds-lang/src/language/lsp/safe-ds-inlay-hint-provider.ts, packages/safe-ds-lang/src/language/lsp/safe-ds-signature-help-provider.ts, packages/safe-ds-lang/src/language/partialEvaluation/model.ts, packages/safe-ds-lang/src/language/safe-ds-module.ts, packages/safe-ds-lang/src/language/typing/model.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/src/language/validation/inheritance.ts, packages/safe-ds-lang/src/language/validation/other/modules.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/helpers/nodeFinder.ts, packages/safe-ds-lang/tests/helpers/testChecks.test.ts, packages/safe-ds-lang/tests/helpers/testChecks.ts, packages/safe-ds-lang/tests/helpers/testRanges.ts, packages/safe-ds-lang/tests/language/generation/creator.ts, packages/safe-ds-lang/tests/language/grammar/creator.ts, packages/safe-ds-lang/tests/language/lsp/formatting/creator.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-inlay-hint-provider.test.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-semantic-token-provider.test.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-signature-help-provider.test.ts, packages/safe-ds-lang/tests/language/partialEvaluation/creator.ts, packages/safe-ds-lang/tests/language/partialEvaluation/safe-ds-partial-evalutator.test.ts, packages/safe-ds-lang/tests/language/typing/type computer/creator.ts, packages/safe-ds-lang/tests/language/typing/type computer/safe-ds-type-computer.test.ts, packages/safe-ds-lang/tests/language/validation/creator.ts, tsconfig.base.json
Closes #24
Implement a signature help provider.
=> feat: signature help

packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/tests/language/typing/safe-ds-type-checker.test.ts
The type checker now checks properly whether a pointer to a class constructor or enum variant constructor is assignable to a callable type.
=> fix: assignability of static type to callable type

packages/safe-ds-lang/src/language/validation/types.ts
Fix several NPEs that could occur during validation because the node passed to the acceptor might be `undefined`. Instead of setting the `property`, as should normally be done, we access the child node directly, since this gives us the correct range.
=> fix: NPEs during validation

packages/safe-ds-lang/src/language/flow/safe-ds-call-graph-computer.ts, packages/safe-ds-lang/src/language/lsp/safe-ds-call-hierarchy-provider.ts, packages/safe-ds-lang/src/language/lsp/safe-ds-document-symbol-provider.ts, packages/safe-ds-lang/src/language/lsp/safe-ds-node-info-provider.ts, packages/safe-ds-lang/src/language/partialEvaluation/safe-ds-partial-evaluator.ts, packages/safe-ds-lang/src/language/safe-ds-module.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/tests/language/lsp/formatting/creator.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-call-hierarchy-provider.test.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-document-symbol-provider.test.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-semantic-token-provider.test.ts, packages/safe-ds-lang/tests/resources/partial evaluation/recursive cases/calls/of enum variants/main.sdstest
Closes #680
Implement a call hierarchy provider to get incoming & outgoing calls.
=> feat: call hierarchy provider

packages/safe-ds-lang/src/language/builtins/safe-ds-annotations.ts, packages/safe-ds-lang/src/language/validation/builtins/pure.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/validation/builtins/annotations/pure/pure parameter must have callable type/main.sdstest
Closes #729
Only allow using the `@Pure` annotation on parameters with a callable type.
=> feat: show an error if a pure parameter does not have a callable type

packages/safe-ds-lang/src/language/lsp/safe-ds-call-hierarchy-provider.ts, packages/safe-ds-lang/src/language/lsp/safe-ds-language-server.ts, packages/safe-ds-lang/src/language/lsp/safe-ds-type-hierarchy-provider.ts, packages/safe-ds-lang/src/language/main.ts, packages/safe-ds-lang/src/language/safe-ds-module.ts, packages/safe-ds-lang/src/language/typing/safe-ds-class-hierarchy.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-type-hierarchy-provider.test.ts
=> feat: type hierarchy provider

docs/language/common/types.md, packages/safe-ds-lang/src/language/validation/other/declarations/typeParameters.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/validation/other/declarations/constraints/type parameter constraints/left operand must be own type parameter/main.sdstest, packages/safe-ds-lang/tests/resources/validation/other/declarations/type parameters/usage/main.sdstest
Closes #748
Show an error if a type parameter of a class is used inside a nested named type declaration.
=> feat: error if type parameter is used in nested named type declaration

packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/src/language/validation/types.ts, packages/safe-ds-lang/tests/resources/validation/types/checking/lists/main.sdstest, packages/safe-ds-lang/tests/resources/validation/types/checking/maps/main.sdstest
Closes #712
Don't allow calls that produce no or multiple results inside list & map literals. In other cases, the existing type checking already took care of this.
=> feat: type checking for list & map literals

packages/safe-ds-lang/src/language/validation/experimentalLanguageFeatures.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/validation/experimental language feature/constraint lists/main.sdstest
When we add more constraint types (e.g. #18), we might also have to change the overall concept. Thus, constraint lists are now marked as experimental (which also applies to the contained constraints).
=> feat: mark constraint lists as experimental

packages/safe-ds-lang/src/language/scoping/safe-ds-scope-provider.ts, packages/safe-ds-lang/src/language/typing/safe-ds-core-types.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/src/resources/builtins/safeds/lang/coreClasses.sdsstub, packages/safe-ds-lang/tests/language/builtins/builtinFilesCorrectness.test.ts, packages/safe-ds-lang/tests/language/scoping/creator.ts, packages/safe-ds-lang/tests/language/scoping/scoping.test.ts, packages/safe-ds-lang/tests/language/typing/safe-ds-class-hierarchy.test.ts, packages/safe-ds-lang/tests/language/typing/type computer/computeClassTypeForLiteralType.test.ts
Closes #80
Resolved accessed members on literals and literal types.
=> feat: scoping for member access on literals and literal types

packages/safe-ds-lang/src/language/validation/experimentalLanguageFeatures.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/validation/experimental language feature/type argument lists/main.sdstest, packages/safe-ds-lang/tests/resources/validation/experimental language feature/type parameter lists/main.sdstest
Closes #753
Mark type parameter lists and type argument lists as experimental. This also applies to the contained type parameters and type arguments.
=> feat: mark type parameter lists and type argument lists as experimental

packages/safe-ds-vscode/package.json, packages/safe-ds-vscode/snippets/safe-ds.json
Closes #756
Various snippets for program elements with lengthy syntax.
=> feat: VS Code snippets

packages/safe-ds-lang/src/language/generation/safe-ds-python-generator.ts, packages/safe-ds-lang/src/language/helpers/nodeProperties.ts, packages/safe-ds-lang/src/language/scoping/safe-ds-scope-provider.ts, packages/safe-ds-lang/src/language/typing/model.ts, packages/safe-ds-lang/src/language/typing/safe-ds-class-hierarchy.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/src/language/validation/builtins/deprecated.ts, packages/safe-ds-lang/src/language/validation/builtins/expert.ts, packages/safe-ds-lang/src/language/validation/inheritance.ts, packages/safe-ds-lang/src/language/validation/names.ts, packages/safe-ds-lang/src/language/validation/other/argumentLists.ts, packages/safe-ds-lang/src/language/validation/other/declarations/annotationCalls.ts, packages/safe-ds-lang/src/language/validation/other/declarations/parameterLists.ts, packages/safe-ds-lang/src/language/validation/other/declarations/parameters.ts, packages/safe-ds-lang/src/language/validation/other/expressions/calls.ts, packages/safe-ds-lang/src/language/validation/other/types/callableTypes.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/src/language/validation/style.ts, packages/safe-ds-lang/tests/language/typing/model.test.ts, packages/safe-ds-lang/tests/language/typing/safe-ds-class-hierarchy.test.ts, packages/safe-ds-lang/tests/language/typing/safe-ds-type-checker.test.ts, packages/safe-ds-lang/tests/language/validation/safe-ds-validator.test.ts, packages/safe-ds-lang/tests/resources/validation/inheritance/overriding method must match overridden method/main.sdstest, packages/safe-ds-lang/tests/resources/validation/types/named types/missing type parameter/main.sdstest, packages/safe-ds-vscode/snippets/safe-ds.json
Closes #639
Show an error if an overriding member does not match the overridden one.
=> feat: ensure an overriding member matches the overridden one

packages/safe-ds-lang/src/language/validation/inheritance.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/validation/inheritance/overriding method must match overridden method/main.sdstest, packages/safe-ds-lang/tests/resources/validation/inheritance/overriding method should differ from overridden method/main.sdstest
Closes #25
Show an info if an overriding member is identical to the overridden one. In this case, it can be removed.
=> feat: info if overriding member is not needed

packages/safe-ds-lang/src/language/helpers/nodeProperties.ts, packages/safe-ds-lang/src/language/scoping/safe-ds-scope-provider.ts, packages/safe-ds-lang/src/language/validation/inheritance.ts, packages/safe-ds-lang/tests/language/scoping/scoping.test.ts, packages/safe-ds-lang/tests/resources/validation/inheritance/overriding method should differ from overridden method/safeds lang any.sdstest
Update the scope provider, so core declarations can never be overwritten by own declarations.
=> fix: prevent overwriting core declarations

packages/safe-ds-lang/src/helpers/stringUtils.ts, packages/safe-ds-lang/src/language/documentation/safe-ds-documentation-provider.ts, packages/safe-ds-lang/tests/helpers/stringUtils.test.ts, packages/safe-ds-lang/tests/language/documentation/safe-ds-documentation-provider.test.ts, packages/safe-ds-lang/tests/language/lsp/formatting/creator.ts
Closes partially #669
Write tag in bold and the declaration name in italics for rendered `@param`, `@result` and `@typeParam` tags.
=> feat: customize rendering of `@param`, `@result`, and `@typeParam` tags

packages/safe-ds-lang/src/language/builtins/safe-ds-annotations.ts, packages/safe-ds-lang/src/language/helpers/safe-ds-node-mapper.ts, packages/safe-ds-lang/tests/language/helpers/safe-ds-node-mapper/callToParameterValue.test.ts
Move the method `callToParameterValue` to `SafeDsNodeMapper`. Previously, it was private in `SafeDsAnnotations`. Given a call and a parameter (or its name), it returns the value assigned to the parameter in the call. It also takes default values into account.
=> refactor: move `callToParameterValue` into `NodeMapper`

packages/safe-ds-lang/src/language/validation/builtins/target.ts, packages/safe-ds-lang/tests/resources/validation/builtins/annotations/target/duplicate target/main.sdstest, packages/safe-ds-lang/tests/resources/validation/builtins/annotations/target/duplicate target/no target annotation.sdstest
Warn about duplicate annotation targets on the actual duplicate targets instead of the containing annotation call.
=> feat: improve location of warning about duplicate annotation target

packages/safe-ds-lang/src/language/validation/builtins/impure.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/validation/builtins/annotations/impure/parameter names must be valid/main.sdstest
Closes #741
A `parameterName` in an `ImpurityReason` must be the name of a parameter in the annotated function. This PR adds validation for this.
=> feat: error if parameter name in impurity reason is invalid

packages/safe-ds-lang/src/language/builtins/safe-ds-annotations.ts, packages/safe-ds-lang/src/language/builtins/safe-ds-enums.ts, packages/safe-ds-lang/src/language/validation/builtins/impure.ts, packages/safe-ds-lang/src/language/validation/builtins/target.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/validation/builtins/annotations/impure/duplicate reason/main.sdstest, packages/safe-ds-lang/tests/resources/validation/builtins/annotations/impure/duplicate reason/no impure annotation.sdstest
Closes #733
Show a warning if an impurity reason is listed multiple times.
=> feat: warn about duplicate impurity reasons

packages/safe-ds-lang/src/language/builtins/safe-ds-enums.ts, packages/safe-ds-lang/src/language/safe-ds-module.ts, packages/safe-ds-lang/src/language/validation/purity.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/validation/purity/callable parameter with unspecified purity/class.sdstest, packages/safe-ds-lang/tests/resources/validation/purity/callable parameter with unspecified purity/function.sdstest, packages/safe-ds-lang/tests/resources/validation/purity/potentially impure parameter must have callable type/main.sdstest, packages/safe-ds-lang/tests/resources/validation/purity/pure and potentially impure callable parameter/main.sdstest
Closes #732
A callable parameter of functions must either be pure or `PotentiallyImpureParameterCall` must be included as an impurity reason on the containing function. However, the two are mutually exclusive. Now an error is shown if none or both are set.
=> feat: check whether purity of callable parameters of functions is set properly

packages/safe-ds-lang/src/language/typing/model.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/tests/language/typing/model.test.ts, packages/safe-ds-lang/tests/resources/typing/declarations/parameters/of block lambdas/that are passed as default values/main.sdstest, packages/safe-ds-lang/tests/resources/typing/declarations/parameters/of expression lambdas/that are passed as default values/main.sdstest, packages/safe-ds-lang/tests/resources/typing/expressions/block lambdas/that are passed as default values/main.sdstest, packages/safe-ds-lang/tests/resources/typing/expressions/expression lambdas/that are passed as default values/main.sdstest
The types of parameter of lambdas that are passed as default value are now inferred from the context.
=> feat: compute types of parameters of lambdas that are passed as default value

packages/safe-ds-lang/src/language/helpers/safe-ds-node-mapper.ts, packages/safe-ds-lang/tests/language/helpers/safe-ds-node-mapper/assigneeToAssignedObject.test.ts
If the RHS of an assignment calls an expression lambda, an incorrect `"assignment/nothing-assigned"` was shown on the first assignee. This PR fixes this.
=> fix: wrong`"assignment/nothing-assigned"` error if RHS calls expression lambda

packages/safe-ds-lang/src/language/flow/safe-ds-call-graph-computer.ts, packages/safe-ds-lang/src/language/generation/safe-ds-python-generator.ts, packages/safe-ds-lang/src/language/purity/model.ts, packages/safe-ds-lang/src/language/purity/safe-ds-purity-computer.ts, packages/safe-ds-lang/src/language/validation/other/statements/statements.ts, packages/safe-ds-lang/tests/language/documentation/safe-ds-comment-provider.test.ts, packages/safe-ds-lang/tests/language/documentation/safe-ds-documentation-provider.test.ts, packages/safe-ds-lang/tests/language/generation/safe-ds-python-generator.test.ts, packages/safe-ds-lang/tests/language/grammar/safe-ds-grammar.test.ts, packages/safe-ds-lang/tests/language/helpers/safe-ds-node-mapper/argumentToParameter.test.ts, packages/safe-ds-lang/tests/language/helpers/safe-ds-node-mapper/assigneeToAssignedObject.test.ts, packages/safe-ds-lang/tests/language/helpers/safe-ds-node-mapper/callToCallable.test.ts, packages/safe-ds-lang/tests/language/helpers/safe-ds-node-mapper/parameterToReferences.test.ts, packages/safe-ds-lang/tests/language/helpers/safe-ds-node-mapper/placeholdersToReferences.test.ts, packages/safe-ds-lang/tests/language/helpers/safe-ds-node-mapper/resultToYields.test.ts, packages/safe-ds-lang/tests/language/helpers/safe-ds-node-mapper/typeArgumentToTypeParameter.test.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-call-hierarchy-provider.test.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-document-symbol-provider.test.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-inlay-hint-provider.test.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-semantic-token-provider.test.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-signature-help-provider.test.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-type-hierarchy-provider.test.ts, packages/safe-ds-lang/tests/language/partialEvaluation/safe-ds-partial-evalutator.test.ts, packages/safe-ds-lang/tests/language/purity/model.test.ts, packages/safe-ds-lang/tests/language/purity/safe-ds-purity-computer.test.ts, packages/safe-ds-lang/tests/language/typing/safe-ds-class-hierarchy.test.ts, packages/safe-ds-lang/tests/language/typing/type computer/safe-ds-type-computer.test.ts, packages/safe-ds-lang/tests/language/validation/safe-ds-validator.test.ts, packages/safe-ds-lang/tests/language/workspace/safe-ds-workspace-manager.test.ts
Endless recursion is now included in the inferred impurity reasons of an expression/callable.
=> feat: add endless recursion as an impurity reason

packages/safe-ds-lang/src/language/partialEvaluation/safe-ds-partial-evaluator.ts, packages/safe-ds-lang/tests/language/partialEvaluation/safe-ds-partial-evalutator.test.ts, packages/safe-ds-lang/tests/resources/partial evaluation/recursive cases/infix operations/and/main.sdstest, packages/safe-ds-lang/tests/resources/partial evaluation/recursive cases/infix operations/and/short circuiting.sdstest, packages/safe-ds-lang/tests/resources/partial evaluation/recursive cases/infix operations/elvis/main.sdstest, packages/safe-ds-lang/tests/resources/partial evaluation/recursive cases/infix operations/elvis/short circuiting.sdstest, packages/safe-ds-lang/tests/resources/partial evaluation/recursive cases/infix operations/or/main.sdstest, packages/safe-ds-lang/tests/resources/partial evaluation/recursive cases/infix operations/or/short circuiting.sdstest, packages/safe-ds-lang/tests/resources/typing/expressions/operations/elvis/non nullable left operand.sdstest, packages/safe-ds-lang/tests/resources/typing/expressions/operations/elvis/nullable left operand.sdstest
Closes #15
Evaluate `and`, `or`, and `?:` if the RHS has no side effects and the LHS determines the result.
=> feat: short-circuit `and`, `or`, and `?:` if RHS has no side effects

packages/safe-ds-lang/src/language/flow/model.ts, packages/safe-ds-lang/src/language/flow/safe-ds-call-graph-computer.ts, packages/safe-ds-lang/src/language/partialEvaluation/model.ts, packages/safe-ds-lang/src/language/purity/model.ts, packages/safe-ds-lang/src/language/purity/safe-ds-purity-computer.ts, packages/safe-ds-lang/tests/language/partialEvaluation/model.test.ts, packages/safe-ds-lang/tests/language/purity/model.test.ts, packages/safe-ds-lang/tests/language/purity/safe-ds-purity-computer.test.ts, packages/safe-ds-lang/tests/resources/call graph/callable type call.sdstest, packages/safe-ds-lang/tests/resources/partial evaluation/base cases/block lambdas/main.sdstest, packages/safe-ds-lang/tests/resources/partial evaluation/base cases/expression lambdas/main.sdstest, packages/safe-ds-lang/tests/resources/partial evaluation/recursive cases/infix operations/elvis/main.sdstest, packages/safe-ds-lang/tests/resources/validation/other/statements/assignments/has no effect/main.sdstest, packages/safe-ds-lang/tests/resources/validation/other/statements/expression statements/has no effect/main.sdstest
Statements that called parameters (with unknown value) or unknown callables were wrongly marked as unused. Because if this, an incorrect warning was shown and no code was generated for them.
=> fix: wrong detection of useless statements that call parameters/unknown callables

packages/safe-ds-lang/src/language/validation/purity.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/generation/statements/assignment/input.sdstest, packages/safe-ds-lang/tests/resources/generation/statements/expression statement/input.sdstest, packages/safe-ds-lang/tests/resources/validation/purity/impure callable passed to pure parameter/arguments.sdstest, packages/safe-ds-lang/tests/resources/validation/purity/impure callable passed to pure parameter/default values.sdstest
Closes #730
Show an error if an impure callable is passed to a pure parameter.
=> feat: error if impure callable is passed to pure parameter

packages/safe-ds-lang/src/language/lsp/safe-ds-signature-help-provider.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-signature-help-provider.test.ts
Closes #791
Optional parameters in the signature help now get highlighted properly.
=> fix: signature help for optional parameters

packages/safe-ds-lang/src/language/flow/safe-ds-call-graph-computer.ts, packages/safe-ds-lang/tests/resources/call graph/block lambda call/default value/previous parameter.sdstest, packages/safe-ds-lang/tests/resources/call graph/class call/default value/previous parameter.sdstest, packages/safe-ds-lang/tests/resources/call graph/default value handling in entry point.sdstest, packages/safe-ds-lang/tests/resources/call graph/enum variant call/default value/previous parameter.sdstest, packages/safe-ds-lang/tests/resources/call graph/expression lambda call/default value/previous parameter.sdstest, packages/safe-ds-lang/tests/resources/call graph/function call/default value/previous parameter.sdstest, packages/safe-ds-lang/tests/resources/call graph/segment call/default value/previous parameter.sdstest
Consider the following code:
```
@Pure fun default() -> r: Any
segment mySegment(param: () -> () = default) {
»param()«;
}
```
When computing the call graph for the `param()` call, we were previously always substituting `param` with its default value, since the parameter substitutions were empty in the entry point. Because of this, we were incorrectly considering the `param()` call as pure, just like the segment `mySegment`.
=> fix: handling of default values in entry point of call graph computation

packages/safe-ds-lang/src/language/partialEvaluation/safe-ds-partial-evaluator.ts, packages/safe-ds-lang/tests/resources/partial evaluation/recursive cases/calls/recursion/main.sdstest
The partial evaluator was also evaluating recursive calls, which led to a stack overflow. We now check whether the call is recursive before evaluating it.
=> fix: stack overflow when evaluating recursive calls

packages/safe-ds-lang/src/language/helpers/nodeProperties.ts, packages/safe-ds-lang/src/language/purity/safe-ds-purity-computer.ts, packages/safe-ds-lang/tests/language/flow/safe-ds-call-graph-computer.test.ts, packages/safe-ds-lang/tests/language/purity/safe-ds-purity-computer.test.ts
Calls of function parameters inside the same function lead to a stack overflow when computing purity, like in the following example:
```
package test
@Pure fun default() -> result: Any
@Pure fun myFunction(
f: () -> (result: Any) = default,
g: Any = f() // <--
)
```
1. "f()" calls the parameter "f".
2. For called parameters, we check whether they must be pure. Otherwise, we add an impurity reason.
3. This requires the computation of the impurity reasons of the containing callable "myFunction".
4. This requires visiting all calls inside "myFunction".
5. This includes the call of "f()".
6. We compute the impurity reasons of "f()" and are back at the start.
=> fix: potential stack overflow when computing impurity reasons

packages/safe-ds-vscode/src/extension/pythonServer.ts
If the child process does not respond, tree kill does not wait for the process to end.
This may cause VS Code to continue with shutting down, killing the first process of the tree only.
The reference to the tree is then lost, and tree-kill can no longer continue killing the other processes.
To fix this, await the completion of tree-kill.
Added some more logging
=> fix: Wait for tree-kill during deactivation if child process does not respond

packages/safe-ds-lang/src/language/generation/safe-ds-python-generator.ts, packages/safe-ds-vscode/src/extension/pythonServer.ts
Closes #810
- fix: use correct paths and module names to correctly execute Safe-DS files that contain spaces and fix access to source mappings for these files
=> fix: use correct paths and module names to correctly execute Safe-DS files with spaces

packages/safe-ds-lang/src/language/helpers/nodeProperties.ts, packages/safe-ds-lang/src/language/lsp/safe-ds-document-symbol-provider.ts, packages/safe-ds-lang/src/language/lsp/safe-ds-rename-provider.ts, packages/safe-ds-lang/src/language/safe-ds-module.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-rename-provider.test.ts
Closes #635
Declarations that are imported under an alias are now correctly ignored during renaming. The renaming behavior is always the same, no matter whether it is triggered on a declaration or any reference. An alias can only be changed manually.
=> fix: renaming of declarations that are imported under an alias

packages/safe-ds-lang/src/language/helpers/nodeProperties.ts, packages/safe-ds-lang/src/language/validation/other/declarations/typeParameters.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/validation/other/declarations/type parameters/usage of variant type parameter/contravariant type parameter.sdstest, packages/safe-ds-lang/tests/resources/validation/other/declarations/type parameters/usage of variant type parameter/covariant type parameter.sdstest, packages/safe-ds-lang/tests/resources/validation/other/declarations/type parameters/usage of variant type parameter/invariant type parameter.sdstest, packages/safe-ds-lang/tests/resources/validation/other/declarations/type parameters/usage of variant type parameter/resources.sdstest, packages/safe-ds-lang/tests/resources/validation/other/declarations/type parameters/usage of variant type parameter/usage of class type parameters.sdstest
Closes #743
* Covariant type parameters must only be used in covariant positions.
* Contravariant type parameters must only be used in contravariant positions.
This PR adds checks for this.
=> feat: check position of usages of variant type parameters

packages/safe-ds-lang/src/language/helpers/nodeProperties.ts, packages/safe-ds-lang/src/language/validation/other/declarations/typeParameters.ts, packages/safe-ds-lang/tests/resources/validation/other/declarations/type parameters/usage of variant type parameter/covariant type parameter.sdstest
Previously, an incorrect error was shown when a covariant type parameter was used in the own constructor of the generic class. This PR removes this error.
=> fix: allow usage of covariant type parameters in own constructor

packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/tests/resources/typing/expressions/member accesses/on class with type parameters/main.sdstest
Closes #863
We now also substitute type parameters when computing the type for inherited members in a member access. Example:
```
class C<T> {
attr member: T
}
class D sub C<Int>
segment mySegment(p: D) {
val a = p.member;
}
```
`a` now get the correct type `Int` (previously it was `T`).
=> feat: substitute type parameters when computing type of inherited members

packages/safe-ds-lang/src/language/validation/inheritance.ts, packages/safe-ds-lang/tests/resources/validation/inheritance/overriding method must match overridden method/main.sdstest, packages/safe-ds-lang/tests/resources/validation/inheritance/overriding method must match overridden method/type parameters.sdstest, packages/safe-ds-lang/tests/resources/validation/inheritance/overriding method should differ from overridden method/main.sdstest, packages/safe-ds-lang/tests/resources/validation/inheritance/overriding method should differ from overridden method/purity.sdstest, packages/safe-ds-lang/tests/resources/validation/inheritance/overriding method should differ from overridden method/type parameters.sdstest
Closes #862
We now substitute type parameter when checking whether a class member gets overridden properly and whether the overriding is actually necessary. Example:
```
class MySuperClass<T> {
attr member: T
}
class MyClass1 sub MySuperClass<Number> {
attr member: Int // OK
}
class MyClass2 sub MySuperClass<Number> {
attr member: String // Not OK
}
class MyClass3 sub MySuperClass<Number> {
attr member: Number // Unnecessary
}
```
=> feat: substitute type parameters when checking assignability of overriding members

packages/safe-ds-lang/src/language/partialEvaluation/model.ts, packages/safe-ds-lang/src/language/typing/model.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/tests/language/typing/model.test.ts, packages/safe-ds-lang/tests/language/typing/type checker/isAssignableTo.test.ts, packages/safe-ds-lang/tests/language/typing/type computer/lowestCommonSupertype.test.ts, packages/safe-ds-lang/tests/resources/typing/expressions/literals/main.sdstest, packages/safe-ds-lang/tests/resources/typing/expressions/member accesses/on class with type parameters/main.sdstest, packages/safe-ds-lang/tests/resources/typing/expressions/member accesses/to other/main.sdstest, packages/safe-ds-lang/tests/resources/typing/simplification/remove duplicate constants from literal types/main.sdstest, packages/safe-ds-lang/tests/resources/typing/simplification/remove unneeded entries from union types/main.sdstest, packages/safe-ds-lang/tests/resources/typing/simplification/replace empty literal types with Nothing/main.sdstest, packages/safe-ds-lang/tests/resources/typing/simplification/replace empty union types with Nothing/main.sdstest, packages/safe-ds-lang/tests/resources/typing/simplification/replace literals types that allow only null with NothingNullable/main.sdstest, packages/safe-ds-lang/tests/resources/typing/simplification/unwrap/main.sdstest, packages/safe-ds-lang/tests/resources/typing/types/literal types/main.sdstest, packages/safe-ds-lang/tests/resources/typing/types/union types/main.sdstest
Apply various simplification rules to computed type to improve their readability:
* Replace `literal<>` with `Nothing`
* Replace `literal<null>` with `Nothing?`
* Remove duplicate entries from literal types
* Replace `union<>` with `Nothing`
* Remove entries from union types that are a subtype of another entry
* Flatten nested union types
=> feat: simplify computed types

packages/safe-ds-lang/src/language/validation/other/declarations/typeParameters.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/validation/other/declarations/type parameters/usage of variant type parameter/contravariant type parameter.sdstest, packages/safe-ds-lang/tests/resources/validation/other/declarations/type parameters/usage of variant type parameter/covariant type parameter.sdstest, packages/safe-ds-lang/tests/resources/validation/other/declarations/type parameters/usage of variant type parameter/invariant type parameter.sdstest, packages/safe-ds-lang/tests/resources/validation/other/declarations/type parameters/variance only on classes/invariant.sdstest, packages/safe-ds-lang/tests/resources/validation/other/declarations/type parameters/variance only on classes/variant.sdstest
Variant type parameters may only occur on classes. This PR adds validation for this.
=> feat: error if type parameters of functions are variant

packages/safe-ds-lang/src/language/typing/model.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/tests/language/typing/model.test.ts, packages/safe-ds-lang/tests/resources/typing/simplification/merge literal types in union types/main.sdstest, packages/safe-ds-lang/tests/resources/typing/simplification/remove unneeded entries from union types/main.sdstest, packages/safe-ds-lang/tests/resources/typing/simplification/replace literals types that allow only null with NothingOrNull/main.sdstest
* Merge literal types in union types (`union<literal<1>, literal<2>` becomes `literal<1, 2>`).
* Unwrap type parameter substitutions in class type (`C<union<Int>>` becomes `C<Int>`).
=> feat: improve type simplification

packages/safe-ds-lang/src/language/validation/other/declarations/typeParameters.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/validation/other/declarations/constraints/type parameter bounds/left operand must be own type parameter/main.sdstest, packages/safe-ds-lang/tests/resources/validation/other/declarations/type parameters/bound must be named type/main.sdstest
Closes #876
Add a check to ensure that the bound of a type parameter is a named type.
=> feat: check whether type parameter bounds are named types

packages/safe-ds-lang/src/language/helpers/nodeProperties.ts, packages/safe-ds-lang/src/language/validation/other/declarations/typeParameters.ts, packages/safe-ds-lang/tests/resources/generation/expressions/indexed access/input.sdstest, packages/safe-ds-lang/tests/resources/validation/other/declarations/type parameters/multiple bounds/main.sdstest
Closes #881
We now correctly show an error if a type parameter has multiple lower/upper bounds but occurs as the right operand in subsequent bounds.
=> fix: check for duplicate bounds if type parameters occur as right operand

packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/tests/language/typing/type checker/isAssignableTo.test.ts
Closes #877
The type checker can now properly check assignability of and to type parameter types.
=> feat: handle type parameter types in type checker

packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/src/language/validation/other/declarations/typeParameters.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/validation/other/declarations/type parameters/lower bound must be assignable to upper bound/main.sdstest
Closes #875
Show an error if the lower bound of a type parameter is not assignable to its upper bound. In this case, there is no valid substitution for the type parameter.
=> feat: check whether lower and upper bounds of a type parameter are compatible

docs/README.md, package-lock.json, packages/safe-ds-lang/package.json, packages/safe-ds-lang/src/language/runner/safe-ds-runner.ts
- check the runner version to be compatible before starting the runner
Closes #880
=> feat: check the runner version to be compatible

packages/safe-ds-lang/src/language/scoping/safe-ds-scope-provider.ts, packages/safe-ds-lang/tests/resources/scoping/member accesses/on type parameters/main.sdstest
The scope provider can now handle member accesses where the receiver has type parameter type. This type is replaced by its upper bound, before name resolution continues as before.
=> feat: scoping for member accesses if receiver has type parameter type

packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/src/language/validation/inheritance.ts, packages/safe-ds-lang/tests/language/typing/type computer/streamSupertypes.test.ts, packages/safe-ds-lang/tests/resources/validation/inheritance/must inherit only classes/class with parent types.sdstest, packages/safe-ds-lang/tests/resources/validation/inheritance/must inherit only classes/class without parent types.sdstest, packages/safe-ds-lang/tests/resources/validation/inheritance/must not be nullable/class with parent types.sdstest
Only allow non-nullable class types as the parent types of a class.
=> feat: error if parent type is nullable

packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/src/language/validation/other/expressions/chainedExpressions.ts, packages/safe-ds-lang/src/language/validation/style.ts, packages/safe-ds-lang/tests/resources/validation/other/expressions/chained expression/missing null safety/main.sdstest, packages/safe-ds-lang/tests/resources/validation/style/unnecessary elvis operator/main.sdstest, packages/safe-ds-lang/tests/resources/validation/style/unnecessary null safety/main.sdstest
Type parameter types can be nullable in two different way:
1. They are explicitly declared as nullable using a `?`.
2. They have a nullable upper bound.
This PR now updates various checks to also consider the 2. option:
* Info: Elvis operator is unnecessary, because its left operand is never `null`.
* Info: Null-safe index access/member access is unnecessary, because the receiver is never `null`.
* Error: Index access/member access must be null-safe, because the receiver can be `null`.
=> feat: consider nullability of upper type parameter bound in various checks

packages/safe-ds-lang/src/language/typing/model.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/src/language/validation/inheritance.ts, packages/safe-ds-lang/tests/language/typing/model.test.ts, packages/safe-ds-lang/tests/language/typing/type checker/canBeTypeOfConstantParameter.test.ts, packages/safe-ds-lang/tests/language/typing/type checker/isSubOrSupertypeOf.test.ts, packages/safe-ds-lang/tests/language/typing/type computer/computeClassTypeForLiteralType.test.ts, packages/safe-ds-lang/tests/resources/typing/simplification/remove unneeded entries from union types/main.sdstest
Consider the `class C<T> where { T sub Any }`. Previously, the type `union<T, Any>` was simplified to `T`, while the type `union<Any, T>` was simplified to `Any`. Now the simplified type is `T` in both cases. We chose the type parameter type, since it can be narrower if it has a lower bound.
=> feat: simplify union types containing type parameter types disregarding entry order

packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/tests/resources/typing/lowest common supertype/class type and class type/main.sdstest, packages/safe-ds-lang/tests/resources/typing/lowest common supertype/class type and class type/with type parameters.sdstest, packages/safe-ds-lang/tests/resources/typing/lowest common supertype/class type and type parameter type/main.sdstest, packages/safe-ds-lang/tests/resources/typing/lowest common supertype/enum type and type parameter type/main.sdstest, packages/safe-ds-lang/tests/resources/typing/lowest common supertype/enum variant type and type parameter type/main.sdstest, packages/safe-ds-lang/tests/resources/typing/lowest common supertype/literal type and type parameter type/main.sdstest, packages/safe-ds-lang/tests/resources/typing/lowest common supertype/type parameter type and type parameter type/main.sdstest
Closes partially #860
Invariant/covariant type parameters are now handled when computing the lowest common supertype of a list of types. This functionality is used to compute the type of
* lists (based on their elements)
* maps (based on their keys and values)
* elvis operator (based on their operands).
It's also needed later for #861. Contravariant type parameters need a means to compute the highest common subtype, which will be tackled in a future PR.
=> feat: handle invariant/covariant type parameters when computing lowest common supertype

packages/safe-ds-eda/package.json, packages/safe-ds-lang/src/language/safe-ds-module.ts, packages/safe-ds-lang/src/language/typing/model.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-factory.ts, packages/safe-ds-lang/tests/language/typing/model.test.ts, packages/safe-ds-lang/tests/language/typing/type checker/canBeTypeOfConstantParameter.test.ts, packages/safe-ds-lang/tests/language/typing/type checker/isSubOrSupertypeOf.test.ts, packages/safe-ds-lang/tests/language/typing/type computer/computeClassTypeForLiteralType.test.ts, packages/safe-ds-lang/tests/resources/typing/simplification/unwrap/main.sdstest
* Inject services into type instances where needed.
* Add a factory service to create type instance using a similar interface to the previous constructors.
* Types can now simplify themselves.
* Add an intersection type.
=> refactor: improve type model

packages/safe-ds-lang/src/language/typing/model.ts, packages/safe-ds-lang/tests/language/typing/model.test.ts, packages/safe-ds-lang/tests/resources/typing/declarations/enum variants/main.sdstest, packages/safe-ds-lang/tests/resources/typing/expressions/calls/of enum variants/main.sdstest, packages/safe-ds-lang/tests/resources/typing/expressions/member accesses/to enum variants/main.sdstest, packages/safe-ds-lang/tests/resources/typing/highest common subtype/class type and enum variant/main.sdstest, packages/safe-ds-lang/tests/resources/typing/highest common subtype/enum type and enum variant type/main.sdstest, packages/safe-ds-lang/tests/resources/typing/highest common subtype/enum variant type and enum variant type/main.sdstest, packages/safe-ds-lang/tests/resources/typing/lowest common supertype/enum variant type and enum variant type/main.sdstest, packages/safe-ds-lang/tests/resources/typing/lowest common supertype/enum variant type and type parameter type/main.sdstest, packages/safe-ds-lang/tests/resources/typing/lowest common supertype/singular type after simplification/main.sdstest, packages/safe-ds-lang/tests/resources/typing/types/member types/main.sdstest
Closes #902
Given the code 
```
enum Kernel {
Linear
Poly(degree: Int)
}
```
calling `toString` on the type `Kernel.Linear` now also returns `Kernel.Linear`. Previously, it returned `Linear`, i.e. only the name of the enum variant.
=> feat: include enum name in string conversion of enum variant types

packages/safe-ds-lang/src/language/grammar/safe-ds-value-converter.ts, packages/safe-ds-lang/src/language/partialEvaluation/model.ts, packages/safe-ds-lang/tests/language/grammar/safe-ds-value-converter.test.ts, packages/safe-ds-lang/tests/resources/partial evaluation/base cases/string literals (without interpolation)/main.sdstest, packages/safe-ds-lang/tests/resources/partial evaluation/recursive cases/template strings/main.sdstest
Closes #904
Newlines, tabs, etc. now get escaped when converting a string constant to a string. This affects inlay hints for literal types, for example.
=> feat: escape characters in string conversion of string constants

packages/safe-ds-vscode/src/extension/mainClient.ts
Closes #910
Shorten the message in the error popup if some files in the workspace have errors and the runner is started:
=> feat: shorter message if runner is started but files have errors

packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/tests/language/typing/type checker/isSubOrSupertypeOf.test.ts
Related to #915
As described in #915, the code
```
fun f<T>(p: (a: T) -> b: String)
pipeline myPipeline {
// Expected type '(a: T) -> (b: String)' but got '(a: String) -> (result: String)'
f((a: Int) -> a);
}
```
currently shows an error due to a parameter mismatch (contravariant context). In a covariant context (e.g. for results), however, no such error is shown. That's because when checking whether a type `T1` can be assigned to a type `T2`, we used to replace a type parameter type as `T1` with its **upper** bound (strict) and as `T2` with its upper bound (lenient).
We now instead replace a type parameter as `T1` with its **lower** bound (lenient). This simply checks whether there are any substitutions for `T1` that could let the subtype relation become true.
=> fix: lenient type checking involving type parameter types

packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/src/language/validation/types.ts, packages/safe-ds-lang/tests/resources/validation/types/checking/default values/with type parameters.sdstest, packages/safe-ds-lang/tests/resources/validation/types/checking/type parameter bounds for default values/main.sdstest, packages/safe-ds-lang/tests/resources/validation/types/checking/type parameter bounds for named types/main.sdstest
Closes partially #614
* Ensure default values of type parameters respect their upper bound.
* Ensure type arguments of named types respect the upper bound of the corresponding type parameter.
=> feat: check type parameter bounds for default values and named types

packages/safe-ds-lang/src/language/helpers/nodeProperties.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/tests/resources/typing/expressions/calls/type parameter inference/clamp to upper bound/main.sdstest, packages/safe-ds-lang/tests/resources/typing/expressions/calls/type parameter inference/deep nesting/main.sdstest, packages/safe-ds-lang/tests/resources/typing/expressions/calls/type parameter inference/default value of parameter/main.sdstest, packages/safe-ds-lang/tests/resources/typing/expressions/calls/type parameter inference/default value of type parameter/main.sdstest, packages/safe-ds-lang/tests/resources/typing/expressions/calls/type parameter inference/differing variance/main.sdstest, packages/safe-ds-lang/tests/resources/typing/expressions/calls/type parameter inference/multiple contravariant/main.sdstest, packages/safe-ds-lang/tests/resources/typing/expressions/calls/type parameter inference/multiple covariant/main.sdstest, packages/safe-ds-lang/tests/resources/typing/expressions/calls/type parameter inference/single contravariant/main.sdstest, packages/safe-ds-lang/tests/resources/typing/expressions/calls/type parameter inference/single covariant/main.sdstest
Closes #861
Compute and apply substitutions for the type parameters of a called callable.
=> feat: compute type parameters for calls

packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/tests/resources/typing/expressions/calls/type parameter inference/clamp to upper bound/main.sdstest
The default value of a type parameter is now clamped to its upper bound during inference of type parameters for calls.
=> feat: clamp default values of parameter types to upper bound

packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/src/language/validation/inheritance.ts, packages/safe-ds-lang/tests/resources/typing/expressions/operations/arithmetic/main.sdstest, packages/safe-ds-lang/tests/resources/validation/inheritance/overriding method must match overridden method/type parameters.sdstest, packages/safe-ds-lang/tests/resources/validation/inheritance/overriding method should differ from overridden method/type parameters.sdstest, packages/safe-ds-lang/tests/resources/validation/types/checking/indexed access receiver/main.sdstest
Closes #917
When checking whether overriding is legal and needed, we now use strict type checking and correctly substitute type parameters.
=> feat: substitute type parameters when checking overridden members

packages/safe-ds-lang/src/language/typing/model.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/src/language/validation/inheritance.ts, packages/safe-ds-lang/src/language/validation/other/expressions/infixOperations.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/src/language/validation/types.ts, packages/safe-ds-lang/tests/language/typing/type checker/isSubOrSupertypeOf.test.ts, packages/safe-ds-lang/tests/resources/validation/types/checking/arguments/with type parameters.sdstest, packages/safe-ds-lang/tests/resources/validation/types/checking/default values/with type parameters.sdstest, packages/safe-ds-lang/tests/resources/validation/types/checking/indexed access on list/main.sdstest, packages/safe-ds-lang/tests/resources/validation/types/checking/indexed access on map/main.sdstest, packages/safe-ds-lang/tests/resources/validation/types/checking/infix operations/main.sdstest, packages/safe-ds-lang/tests/resources/validation/types/checking/prefix operations/main.sdstest, packages/safe-ds-lang/tests/resources/validation/types/checking/type parameter bounds for default values/main.sdstest, packages/safe-ds-lang/tests/resources/validation/types/checking/type parameter bounds for named types/main.sdstest
Closes #915
* Substitute type parameter when type checking calls.
* Remove lenient type checking mode. We now use the strict mode everywhere, which means when calling `isSubtypeOf(type, other)` that the upper bound of `type` must be a subtype of the lower bound of `other`.
=> feat: substitute type parameter when type checking calls

packages/safe-ds-vscode/package.json, packages/safe-ds-vscode/src/extension/commands/dumpDiagnostics.ts, packages/safe-ds-vscode/src/extension/commands/openDiagnosticsDumps.ts, packages/safe-ds-vscode/src/extension/mainClient.ts
Closes #927
Add two new commands:
* Dump Diagnostics to JSON
* Open Diagnostics Dumps in New VS Code Window (to quickly discover them)
=> feat: VS Code command to dump diagnostics into a JSON file

packages/safe-ds-lang/src/language/validation/types.ts, packages/safe-ds-lang/tests/resources/validation/types/checking/type casts/main.sdstest
Previously, only expressions of unknown type could be used in type casts. Now, any widening/narrowing type cast is allowed.
=> feat: allow any widening/narrowing type cast

packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/tests/language/typing/type checker/isSubOrSupertypeOf.test.ts
The quantifiers were in the wrong order when checking whether two union types were subtypes of each other: 
Previously, `isSubtypeOf` only returned `true`, if **there was** one entry of `other` that was a supertype **of all** entries of `type`.
Now, it returns `true` if **for all** entries of `type` **there is** one entry of `other` that is a supertype.
=> fix: type checking of two union types

docs/lexer/safe_ds_lexer/_safe_ds_lexer.py, packages/safe-ds-lang/src/language/grammar/safe-ds.langium, packages/safe-ds-lang/src/language/partialEvaluation/safe-ds-partial-evaluator.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/src/language/validation/other/expressions/literals.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/language/partialEvaluation/canBeValueOfConstantParameter.test.ts, packages/safe-ds-lang/tests/language/typing/type computer/computeUpperBound.test.ts, packages/safe-ds-lang/tests/resources/formatting/expressions/literals/unknown.sdstest, packages/safe-ds-lang/tests/resources/grammar/expressions/literals/good-unknown.sdstest, packages/safe-ds-lang/tests/resources/grammar/keywords as names/bad-unescaped unknown.sdstest, packages/safe-ds-lang/tests/resources/grammar/keywords as names/good-escapedKeywords.sdstest, packages/safe-ds-lang/tests/resources/partial evaluation/base cases/unknown literals/main.sdstest, packages/safe-ds-lang/tests/resources/typing/expressions/literals/main.sdstest, packages/safe-ds-lang/tests/resources/typing/highest common subtype/unknown type/main.sdstest, packages/safe-ds-lang/tests/resources/typing/lowest common supertype/singular type after simplification/main.sdstest, packages/safe-ds-lang/tests/resources/typing/lowest common supertype/unknown type/main.sdstest, packages/safe-ds-lang/tests/resources/validation/other/expressions/literals/unknown must only be used as default value of stub/main.sdstest, packages/safe-ds-vscode/syntaxes/safe-ds.tmLanguage.json
Closes #951
Add a new literal `unknown` that can be used to mark parameters as optional if the exact default value of a class/enum variant/function parameter is unknown. This literal can be used nowhere else.
=> feat: `unknown` default value of stub parameters

docs/language/common/comments.md, docs/stdlib/safeds/data/tabular/containers/Column.md, docs/stdlib/safeds/data/tabular/containers/Table.md, packages/safe-ds-lang/src/language/documentation/safe-ds-documentation-provider.ts, packages/safe-ds-lang/src/language/generation/safe-ds-markdown-generator.ts, packages/safe-ds-lang/src/resources/builtins/safeds/data/tabular/containers/column.sdsstub, packages/safe-ds-lang/src/resources/builtins/safeds/data/tabular/containers/table.sdsstub, packages/safe-ds-lang/tests/language/documentation/safe-ds-documentation-provider.test.ts
`{@link }` tags can now also contain name paths to access instance & static members of classes and variants of enums. Refer to the documentation for usage instructions.
=> feat: resolve name paths in `{@link }` tags in documentation

docs/language/common/comments.md, packages/safe-ds-lang/src/language/documentation/safe-ds-documentation-provider.ts, packages/safe-ds-lang/src/language/validation/names.ts, packages/safe-ds-lang/tests/language/documentation/safe-ds-documentation-provider.test.ts, packages/safe-ds-lang/tests/resources/validation/names/duplicates/in class/main.sdstest
* Classes can no longer have instance and static members with the same name. This was very confusing and frequently required special handling (e.g. `.` vs. `#` separators for name paths in `{@link}` tags.
* `.` is now the only separator in name paths of `{@link}` tags, regardless of whether it's an instance or static member.
=> feat: forbid instance and static class members with same name

packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/src/language/validation/types.ts, packages/safe-ds-lang/tests/resources/validation/types/checking/type casts/main.sdstest
If a type cast can never succeed, it is now marked completely as erroneous. Previously, only its left operand was marked, which makes little sense since both operands determine whether the cast is legal.
=> feat: mark entire type cast as wrong if cast is impossible

packages/safe-ds-lang/src/language/lsp/safe-ds-inlay-hint-provider.ts, packages/safe-ds-lang/src/language/workspace/safe-ds-settings-provider.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-inlay-hint-provider.test.ts, packages/safe-ds-vscode/package.json
Add optional inlay hints for the inferred types of lambda parameters without manifest types.
=> feat: inlay hints for inferred types of lambda parameters

packages/safe-ds-lang/src/language/lsp/safe-ds-completion-provider.ts, packages/safe-ds-lang/src/language/lsp/safe-ds-fuzzy-matcher.ts, packages/safe-ds-lang/src/language/safe-ds-module.ts, packages/safe-ds-lang/src/language/validation/other/declarations/typeParameters.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds.completion-provider.test.ts, packages/safe-ds-lang/tests/resources/validation/other/declarations/type parameters/usage of class type parameters/main.sdstest
Closes #998
* Don't suggest references to annotations/pipelines/schemas
* Don't suggest named types pointing to type parameters of containing classes
* Fix an issue in the fuzzy matcher: Now the first character of the query can match the first character of the label or the first character of any word transition (e.g. the `C` in `camelCase` or the `c` in `snake_case`).
=> feat: filter suggestions by node type

packages/safe-ds-lang/src/language/scoping/safe-ds-scope-provider.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds.completion-provider.test.ts
Triggering completion could lead to errors like `Error: SdsMap:result is not a valid reference id.`. These are now caught, since the completion provider inevitably sometimes creates the wrong synthetic nodes before invoking the scope provider.
=> fix: catch internal errors caused by wrong synthetic nodes created by completion provider

packages/safe-ds-lang/src/language/runner/safe-ds-runner.ts, packages/safe-ds-lang/src/language/safe-ds-module.ts, packages/safe-ds-vscode/src/extension/mainClient.ts
As a first step for #1002, register logging callbacks in the `Runner` service instead of the extension.
=> refactor: move logging callbacks into language server

package-lock.json, packages/safe-ds-lang/package.json, packages/safe-ds-lang/src/language/runner/safe-ds-runner.ts, packages/safe-ds-vscode/esbuild.mjs
Previously, source maps were not displayed for me, since the required `wasm` file was not downloaded from NPM. Using `source-maps-js` instead of `source-maps` to consume them, fixes this issue.
=> fix: consumption of source maps

packages/safe-ds-lang/src/language/lsp/safe-ds-messaging-provider.ts, packages/safe-ds-lang/src/language/runner/safe-ds-runner.ts, packages/safe-ds-lang/src/language/safe-ds-module.ts, packages/safe-ds-lang/src/language/workspace/safe-ds-settings-provider.ts, packages/safe-ds-vscode/src/extension/mainClient.ts
Closes #1002
* It's now possible to configure messaging (logging/user messaging) for when creating services.
* The runner now uses the `MessagingProvider` instead of handling messaging on its own.
=> refactor: configure messaging when creating services

packages/safe-ds-lang/src/language/lsp/safe-ds-semantic-token-provider.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-semantic-token-provider.test.ts
Add missing semantic highlighting for block lambda results.
=> feat: semantic highlighting of block lambda results

packages/safe-ds-vscode/src/extension/eda/edaPanel.ts
Disable the global EDA panel cache for now, so tables get refreshed after code changes.
See also https://github.com/Safe-DS/DSL/issues/986#issuecomment-2042731653.
=> fix: disable global EDA panel cache

packages/safe-ds-vscode/src/extension/mainClient.ts
The EDA tool does it own additional type checking to ensure it only opens on `Table`s. This should be removed eventually and type checking should be fully delegated to the language server. For now, this PR also allows opening it on `TaggedTable` and `TimeSeries`.
=> fix: show EDA tool for `TaggedTable` and `TimeSeries`

.github/README.md, docs/README.md, docs/mkdocs.yml
* Separate README for GitHub
* Remove recursive link to full documentation from README of full documentation
* Hide navigation of home page to emphasize the navigation bar at the top
* Some other tweaks the navigation settings
=> docs: improve navigation

packages/safe-ds-lang/src/language/validation/experimentalLanguageFeatures.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/validation/experimental language feature/maps/main.sdstest
Map literals are no longer marked as experimental.
=> feat: map literals are no longer experimental

packages/safe-ds-lang/src/language/index.ts, packages/safe-ds-lang/src/language/runner/safe-ds-runner.ts, packages/safe-ds-lang/src/language/safe-ds-module.ts, packages/safe-ds-vscode/src/extension/commands/installRunner.ts, packages/safe-ds-vscode/src/extension/mainClient.ts
Previously, the runner was not started immediately if the installer did not have to change the runner command, since no event was fired. Now we always force a startup attempt.
=> fix: start runner if configuration did not change after installation

packages/safe-ds-lang/src/language/index.ts, packages/safe-ds-lang/src/language/runner/safe-ds-runner.ts, packages/safe-ds-vscode/package.json, packages/safe-ds-vscode/src/extension/commands/installRunner.ts, packages/safe-ds-vscode/src/extension/commands/updateRunner.ts, packages/safe-ds-vscode/src/extension/mainClient.ts
Add a command to automatically update the runner to a suitable version.
=> feat: updater for the runner

packages/safe-ds-lang/src/language/validation/types.ts, packages/safe-ds-lang/tests/resources/validation/types/checking/infix operations/main.sdsdev, packages/safe-ds-vscode/package.json
If `+` is used for string concatenation, users are now pointed to template strings.
=> feat: better error if `+` is used for string concatenation

packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/tests/resources/typing/declarations/parameters/of block lambdas/that are passed as arguments/with type parameters.sdsdev, packages/safe-ds-lang/tests/resources/typing/declarations/parameters/of expression lambdas/that are passed as arguments/with type parameters.sdsdev, packages/safe-ds-lang/tests/resources/typing/expressions/block lambdas/that are passed as arguments/main.sdsdev, packages/safe-ds-lang/tests/resources/typing/expressions/block lambdas/that are passed as arguments/with type parameters.sdsdev, packages/safe-ds-lang/tests/resources/typing/expressions/expression lambdas/that are passed as arguments/main.sdsdev, packages/safe-ds-lang/tests/resources/typing/expressions/expression lambdas/that are passed as arguments/with type parameters.sdsdev
Closes #1047
Type of lambda parameters can be inferred from the context. Previously, however, type parameter types that were contained in the inferred type were not substituted. Now, they also get inferred from the context.
=> fix: substitute type parameters for lambda parameters

packages/safe-ds-lang/src/language/generation/safe-ds-markdown-generator.ts, packages/safe-ds-lang/src/language/scoping/safe-ds-scope-provider.ts, packages/safe-ds-lang/src/language/typing/model.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-factory.ts, packages/safe-ds-lang/src/language/validation/types.ts, packages/safe-ds-lang/tests/language/typing/model.test.ts, packages/safe-ds-lang/tests/language/typing/type checker/isSubOrSupertypeOf.test.ts, packages/safe-ds-lang/tests/resources/typing/highest common subtype/class type and type variable/main.sdsdev, packages/safe-ds-lang/tests/resources/typing/highest common subtype/enum type and type variable/main.sdsdev, packages/safe-ds-lang/tests/resources/typing/highest common subtype/enum variant type and type variable/main.sdsdev, packages/safe-ds-lang/tests/resources/typing/highest common subtype/type variable and type variable/main.sdsdev, packages/safe-ds-lang/tests/resources/typing/lowest common supertype/class type and type variable/main.sdsdev, packages/safe-ds-lang/tests/resources/typing/lowest common supertype/enum type and type variable/main.sdsdev, packages/safe-ds-lang/tests/resources/typing/lowest common supertype/enum variant type and type variable/main.sdsdev, packages/safe-ds-lang/tests/resources/typing/lowest common supertype/literal type and type variable/main.sdsdev, packages/safe-ds-lang/tests/resources/typing/lowest common supertype/type variable and type variable/main.sdsdev
Rename the type "type parameter type" to "type variable". This is shorter, less cumbersome, and better highlights that this type can be substituted by another type.
=> refactor: rename "type parameter type" to "type variable"

packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/src/language/validation/types.ts, packages/safe-ds-lang/tests/language/typing/type checker/isSubOrSupertypeOf.test.ts, packages/safe-ds-lang/tests/resources/validation/types/checking/arguments/parameter names of callable types.sdsdev
Closes #1046
Names of parameters of passed lambdas no longer matter for type checking. The following code is now legal:
```
@Pure fun f(callback: (p: Int) -> ())
pipeline myPipeline {
f((q) {});
f((q) -> 1);
}
```
=> feat: ignore parameter names when type checking arguments

packages/safe-ds-lang/src/language/lsp/safe-ds-inlay-hint-provider.ts, packages/safe-ds-lang/src/language/typing/model.ts, packages/safe-ds-lang/src/language/workspace/safe-ds-settings-provider.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-inlay-hint-provider.test.ts, packages/safe-ds-lang/tests/language/typing/model.test.ts, packages/safe-ds-vscode/package.json
Closes #1048
Add settings to collapse type arguments of class types and literals of literal types in inlay hints:
* `safe-ds.inlayHints.collapseClassTypes`
* `safe-ds.inlayHints.collapseLiteralTypes`
These types can get quite long, leading to inlay hints that tear the actual program apart. The settings are enabled by default.
=> feat: collapse class/literal types in inlay hints

packages/safe-ds-lang/src/language/typing/safe-ds-class-hierarchy.ts, packages/safe-ds-lang/src/language/validation/names.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/language/typing/safe-ds-class-hierarchy.test.ts, packages/safe-ds-lang/tests/resources/validation/names/duplicates/in class/static and inherited.sdsdev
A class can no longer have a static member with the same name as an inherited member. Otherwise, we would need more complicated `@link` tags in the documentation and more complicated qualified names.
=> feat: error if name of static member equals name of inherited member

docs/api/safeds/data/tabular/containers/Table.md, docs/api/safeds/data/tabular/transformation/InvertibleTableTransformer.md, docs/api/safeds/data/tabular/transformation/TableTransformer.md, docs/api/safeds/lang/Number.md, docs/api/safeds/ml/classical/classification/Classifier.md, docs/api/safeds/ml/classical/regression/Regressor.md, packages/safe-ds-lang/src/language/generation/safe-ds-markdown-generator.ts, packages/safe-ds-lang/src/language/lsp/safe-ds-type-hierarchy-provider.ts, packages/safe-ds-lang/src/language/typing/safe-ds-class-hierarchy.ts, packages/safe-ds-lang/tests/language/typing/safe-ds-class-hierarchy.test.ts, packages/safe-ds-lang/tests/resources/generation/markdown/classes/documented/generated/tests/generation/markdown/classes/documented/MyClass1.md, packages/safe-ds-lang/tests/resources/generation/markdown/classes/documented/generated/tests/generation/markdown/classes/documented/MyClass6.md, packages/safe-ds-lang/tests/resources/generation/markdown/classes/inheritors of builtins/generated/SUMMARY.md, packages/safe-ds-lang/tests/resources/generation/markdown/classes/inheritors of builtins/generated/safeds/lang/Int.md, packages/safe-ds-lang/tests/resources/generation/markdown/classes/inheritors of builtins/generated/safeds/lang/Number.md, packages/safe-ds-lang/tests/resources/generation/markdown/classes/inheritors of builtins/main.sdsstub, packages/safe-ds-lang/tests/resources/generation/markdown/classes/undocumented/generated/tests/generation/markdown/classes/undocumented/MyClass1.md, packages/safe-ds-lang/tests/resources/generation/markdown/classes/undocumented/generated/tests/generation/markdown/classes/undocumented/MyClass6.md
Closes #1036
The direct subclasses of a class are now shown in the documentation with hyperlinks to the respective page.
=> docs: link to direct subclasses

packages/safe-ds-lang/src/language/validation/types.ts, packages/safe-ds-lang/tests/resources/validation/types/checking/default values/parameter names of callable types.sdsdev, packages/safe-ds-lang/tests/resources/validation/types/checking/yields/parameter names of callable types.sdsdev
Parameter names are no longer checked for lambdas used as defaults values and in yields.
=> feat: ignore parameter names for default values and yields

packages/safe-ds-lang/src/resources/builtins/safeds/data/tabular/containers/table.sdsstub, packages/safe-ds-lang/src/resources/builtins/safeds/data/tabular/containers/tagged_table.sdsstub, packages/safe-ds-lang/src/resources/builtins/safeds/data/tabular/containers/time_series.sdsstub, packages/safe-ds-lang/src/resources/builtins/safeds/lang/coreClasses.sdsstub
Allow the callback of `Table.transformColumn` to return `null`.
=> fix: stub for `Table.transformColumn`

packages/safe-ds-lang/src/language/lsp/safe-ds-code-lens-provider.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-code-lens-provider.test.ts, packages/safe-ds-vscode/package.json, packages/safe-ds-vscode/src/extension/mainClient.ts
Pipeline runs are now triggered via a code lens instead of a button. Unlike the button, these don't show up when the runner is not available. They also make it more obvious *which* pipeline is being run.
=> feat: run pipeline via code lens

packages/safe-ds-lang/src/language/communication/safe-ds-messaging-provider.ts, packages/safe-ds-lang/src/language/lsp/safe-ds-code-lens-provider.ts, packages/safe-ds-lang/src/language/lsp/safe-ds-execute-command-handler.ts, packages/safe-ds-lang/src/language/runner/safe-ds-runner.ts, packages/safe-ds-lang/src/language/safe-ds-module.ts, packages/safe-ds-lang/src/language/safe-ds-service-registry.ts, packages/safe-ds-lang/tests/language/communication/safe-ds-messaging-provider.test.ts, packages/safe-ds-vscode/src/extension/eda/apis/runnerApi.ts, packages/safe-ds-vscode/src/extension/logging.ts, packages/safe-ds-vscode/src/extension/mainClient.ts
The `runPipeline` command is now executed in the language server rather than the client. This makes it easier to write extensions for other IDEs that support LSP.
=> refactor: execute `runPipeline` command in language server

packages/safe-ds-lang/src/language/index.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-rename-provider.test.ts, packages/safe-ds-vscode/src/extension/eda/apis/runnerApi.ts
Exploring a table in the following code
```
package bug
pipeline whoSurvived {
val titanic = Table.fromCsvFile("titanic.csv");
val beforeSplit = preprocessBeforeSplit(titanic);
}
segment preprocessBeforeSplit(table: Table) -> result: Table {
yield result = table;
}
```
lead to a runtime error `cannot import name 'preprocessBeforeSplit' from 'bug.gen_titanic' (unknown location)`.
The document that was created for profiling was not properly built, so an incorrect import was created for the segment, even though it was in the same document.
=> fix: import error when exploring tables in pipelines that call segments

packages/safe-ds-lang/src/language/generation/safe-ds-markdown-generator.ts, packages/safe-ds-lang/src/language/helpers/nodeProperties.ts, packages/safe-ds-lang/src/language/lsp/safe-ds-completion-provider.ts, packages/safe-ds-lang/src/language/validation/names.ts, packages/safe-ds-lang/src/language/validation/other/modules.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds.completion-provider.test.ts, packages/safe-ds-lang/tests/resources/validation/names/duplicates/in pipeline file/main.sds, packages/safe-ds-lang/tests/resources/validation/other/modules/declarations in pipeline files/main.sds, packages/safe-ds-vscode/snippets/safe-ds-dev.json, packages/safe-ds-vscode/snippets/safe-ds.json, packages/safe-ds-vscode/syntaxes/safe-ds.tmLanguage.json
Closes #1077
Pipelines files can now contain schemas.
=> feat: allow schemas in pipeline files

packages/safe-ds-lang/src/language/validation/other/declarations/typeParameters.ts, packages/safe-ds-lang/tests/resources/validation/other/declarations/type parameters/insufficient context/main.sdsdev
Closes #1084
Optional type parameters of classes are now always allowed, even if they can never be inferred from their usage in the constructor.
This is useful to initialize them to some default value upon instantiation and override this value later, e.g. in return types of functions. See #1084 for an example.
=> feat: do not check whether optional type parameters of classes can be inferred

packages/safe-ds-lang/src/language/validation/inheritance.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/validation/builtins/annotations/pythonCall/main.sdsdev, packages/safe-ds-lang/tests/resources/validation/inheritance/must not override method with python call annotation/main.sdsdev, packages/safe-ds-lang/tests/resources/validation/inheritance/overriding method must not have python call annotation/main.sdsdev, packages/safe-ds-lang/tests/resources/validation/inheritance/overriding method should differ from overridden method/with python call.sdsdev, packages/safe-ds-lang/tests/resources/validation/inheritance/overriding method should differ from overridden method/with python name.sdsdev, packages/safe-ds-lang/tests/resources/validation/inheritance/python name must match overridden method/main.sdsdev
Add some checks:
* Must not override method with `@PythonCall` annotation
* Overriding method must not have `@PythonCall` annotation
* Python name of overriding method must equal the python name of the overridden method
=> feat: check usages of `@PythonName` and `@PythonCall` on overriding methods

packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/tests/language/typing/type computer/computeUpperBound.test.ts
Related to #1081
Also update the type computer to handle literal types as upper bounds of type parameters.
=> fix: also handle literal types when computing upper bound

packages/safe-ds-lang/src/language/generation/python/safe-ds-python-generator.ts, packages/safe-ds-lang/tests/resources/generation/python/runner integration/expressions/block lambdas/generated/tests/generation/python/runnerIntegration/blockLambdas/gen_input.py, packages/safe-ds-lang/tests/resources/generation/python/runner integration/expressions/block lambdas/generated/tests/generation/python/runnerIntegration/blockLambdas/gen_input.py.map, packages/safe-ds-lang/tests/resources/generation/python/runner integration/expressions/block lambdas/generated/tests/generation/python/runnerIntegration/blockLambdas/gen_input_myPipeline.py, packages/safe-ds-lang/tests/resources/generation/python/runner integration/expressions/block lambdas/input.sdsdev, packages/safe-ds-lang/tests/resources/generation/python/runner integration/expressions/expression lambdas/generated/tests/generation/python/runnerIntegration/expressionLambdas/gen_input.py, packages/safe-ds-lang/tests/resources/generation/python/runner integration/expressions/expression lambdas/generated/tests/generation/python/runnerIntegration/expressionLambdas/gen_input.py.map, packages/safe-ds-lang/tests/resources/generation/python/runner integration/expressions/expression lambdas/generated/tests/generation/python/runnerIntegration/expressionLambdas/gen_input_myPipeline.py, packages/safe-ds-lang/tests/resources/generation/python/runner integration/expressions/expression lambdas/input.sdsdev
Closes #1136
Extra statements that were generated for the expression of an expression lambda were incorrectly placed outside the lambda. This broke the code generation for parameters of expression lambdas that were used as receivers of method calls (see the linked issue).
=> fix: generation of extra statements for parameters of expression lambdas

docs/pipeline-language/statements/assignments.md, packages/safe-ds-lang/src/language/validation/names.ts, packages/safe-ds-lang/src/language/validation/other/declarations/placeholders.ts, packages/safe-ds-lang/tests/resources/validation/names/casing/placeholders.sdsdev, packages/safe-ds-lang/tests/resources/validation/other/declarations/placeholders/unused/main.sdsdev
Closes #1154
Don't show a warning anymore that a placeholder is unused, if its name starts with an underscore.
=> feat: disable "unused" warning for placeholders whose name starts with an underscore

docs/api/safeds/data/tabular/containers/Table.md, docs/pipeline-language/expressions/precedence.md, docs/pipeline-language/expressions/type-casts.md, packages/safe-ds-lang/src/language/grammar/safe-ds.langium, packages/safe-ds-lang/src/resources/builtins/safeds/data/tabular/containers/table.sdsstub, packages/safe-ds-lang/tests/resources/grammar/expressions/type casts/bad-in expression without parentheses.sdsdev, packages/safe-ds-lang/tests/resources/grammar/expressions/type casts/good-in less than comparison.sdsdev
Closes #1150
Type casts now have the lowest precedence. In order to use them inside other expressions, they **must be enclosed in parentheses**.
=> feat: give type casts the lowest precedence

docs/pipeline-language/expressions/precedence.md, docs/pipeline-language/expressions/type-casts.md, packages/safe-ds-lang/src/language/grammar/safe-ds.langium, packages/safe-ds-lang/src/language/lsp/safe-ds-formatter.ts, packages/safe-ds-lang/src/resources/builtins/safeds/data/tabular/containers/row.sdsstub, packages/safe-ds-lang/src/resources/builtins/safeds/data/tabular/containers/table.sdsstub, packages/safe-ds-lang/tests/resources/formatting/expressions/type cast.sdsdev, packages/safe-ds-lang/tests/resources/generation/python/expressions/type casts/input.sdsdev, packages/safe-ds-lang/tests/resources/grammar/expressions/type casts/bad-without closing parenthesis.sdsdev, packages/safe-ds-lang/tests/resources/grammar/expressions/type casts/bad-without opening parenthesis.sdsdev, packages/safe-ds-lang/tests/resources/grammar/expressions/type casts/bad-without parenthesis.sdsdev, packages/safe-ds-lang/tests/resources/grammar/expressions/type casts/good-basic.sdsdev, packages/safe-ds-lang/tests/resources/grammar/expressions/type casts/good-chained.sdsdev, packages/safe-ds-lang/tests/resources/grammar/expressions/type casts/good-in less than comparison with parentheses.sdsdev, packages/safe-ds-lang/tests/resources/partial evaluation/recursive cases/type casts/main.sdsdev, packages/safe-ds-lang/tests/resources/typing/expressions/type casts/main.sdsdev, packages/safe-ds-lang/tests/resources/validation/types/checking/type casts/main.sdsdev
Closes #1150
* Type casts must now have parentheses around their type. This resolves the ambiguity between the less than operator and the start of type argument lists.
* Restore their old, more intuitive precedence.
=> feat: adjust type cast syntax and restore old precedence

packages/safe-ds-lang/src/language/validation/other/imports.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/validation/other/imports/main with issues.sdsdev, packages/safe-ds-lang/tests/resources/validation/other/imports/main without issues.sdsdev
Closes #1153
Remove the warning that an imported package is empty. It was always shown together with an error that a package did not exist. Now, only the error is shown.
=> feat: remove warning that package is empty

packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/tests/resources/typing/declarations/parameters/of block lambdas/that are passed as arguments/with type parameters.sdsdev, packages/safe-ds-lang/tests/resources/typing/declarations/parameters/of expression lambdas/that are passed as arguments/with type parameters.sdsdev, packages/safe-ds-lang/tests/resources/typing/declarations/parameters/scope provider should not cause infinite recursion/main.sdsdev
Due to the interaction between the type computer and the scope provider, the previous approach to prevent endless recursion when computing the type of lambda parameters could fail. This PR provides a more robust implementation to fix this issue.
=> fix: potential stack overflow when computing types of lambda parameters

docs/api/safeds/data/tabular/transformation/TableTransformer.md, docs/api/safeds/ml/classical/classification/AdaBoostClassifier.md, docs/api/safeds/ml/classical/classification/Classifier.md, docs/api/safeds/ml/classical/classification/DecisionTreeClassifier.md, docs/api/safeds/ml/classical/classification/GradientBoostingClassifier.md, docs/api/safeds/ml/classical/classification/KNearestNeighborsClassifier.md, docs/api/safeds/ml/classical/classification/LogisticClassifier.md, docs/api/safeds/ml/classical/classification/RandomForestClassifier.md, docs/api/safeds/ml/classical/classification/SupportVectorClassifier.md, docs/api/safeds/ml/classical/regression/AdaBoostRegressor.md, docs/api/safeds/ml/classical/regression/DecisionTreeRegressor.md, docs/api/safeds/ml/classical/regression/ElasticNetRegressor.md, docs/api/safeds/ml/classical/regression/GradientBoostingRegressor.md, docs/api/safeds/ml/classical/regression/KNearestNeighborsRegressor.md, docs/api/safeds/ml/classical/regression/LassoRegressor.md, docs/api/safeds/ml/classical/regression/LinearRegressor.md, docs/api/safeds/ml/classical/regression/RandomForestRegressor.md, docs/api/safeds/ml/classical/regression/Regressor.md, docs/api/safeds/ml/classical/regression/RidgeRegressor.md, docs/api/safeds/ml/classical/regression/SupportVectorRegressor.md, docs/api/safeds/ml/nn/NeuralNetworkClassifier.md, docs/api/safeds/ml/nn/NeuralNetworkRegressor.md, packages/safe-ds-lang/src/resources/builtins/safeds/ml/classical/classification/Classifier.sdsstub, packages/safe-ds-lang/src/resources/builtins/safeds/ml/classical/regression/Regressor.sdsstub
Override `fit` in `Classifier` and `Regressor`, so metrics can be used on the fitted models.
=> fix: override `fit` in `Classifier` and `Regressor`

packages/safe-ds-vscode/src/extension/eda/apis/runnerApi.ts
Closes #994 
EDA adds another execution in getting the Table placeholder to get column types with the .getColumn().isNumeric call that based on that evals to numeric or categorical type. In future also consider the temporal type, but will have to overhaul the profiling and filters for that.
=> feat: infer column type from runner

packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-code-lens-provider.test.ts
The "print" code lens now also appears for selected nullable types like `Int?`.
=> feat: show "print" code lens for some nullable types

packages/safe-ds-lang/src/language/lsp/safe-ds-signature-help-provider.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-signature-help-provider.test.ts
Closes #1147
Show default values of parameters in the signature help. Previously, it only showed whether a parameter was optional or not.
=> feat: show default values of parameters in signature help

docs/api/safeds/data/tabular/containers/Column.md, docs/api/safeds/data/tabular/containers/Row.md, docs/api/safeds/data/tabular/containers/Table.md, packages/safe-ds-lang/src/language/builtins/safe-ds-classes.ts, packages/safe-ds-lang/src/language/typing/safe-ds-core-types.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/src/language/validation/types.ts, packages/safe-ds-lang/src/resources/builtins/safeds/data/tabular/containers/Column.sdsstub, packages/safe-ds-lang/src/resources/builtins/safeds/data/tabular/containers/Row.sdsstub, packages/safe-ds-lang/src/resources/builtins/safeds/data/tabular/containers/Table.sdsstub, packages/safe-ds-lang/tests/resources/typing/expressions/indexed accesses/on columns/main.sdsdev, packages/safe-ds-lang/tests/resources/typing/expressions/indexed accesses/on lists/main.sdsdev, packages/safe-ds-lang/tests/resources/typing/expressions/indexed accesses/on rows/main.sdsdev, packages/safe-ds-lang/tests/resources/validation/types/checking/indexed access on column/main.sdsdev, packages/safe-ds-lang/tests/resources/validation/types/checking/indexed access on row/main.sdsdev, packages/safe-ds-lang/tests/resources/validation/types/checking/indexed access receiver/main.sdsdev
Allow use of columns and rows as receivers of indexed accesses.
=> feat: indexed access for columns and rows

docs/api/safeds/data/image/containers/Image.md, docs/api/safeds/data/image/containers/ImageList.md, docs/api/safeds/data/tabular/containers/Table.md, packages/safe-ds-lang/src/resources/builtins/safeds/data/image/containers/Image.sdsstub, packages/safe-ds-lang/src/resources/builtins/safeds/data/image/containers/ImageList.sdsstub, packages/safe-ds-lang/src/resources/builtins/safeds/data/tabular/containers/Table.sdsstub
Use correct syntax for links to other API elements in stubs. Previously, they did not work properly in tooltips.
=> fix: use correct link syntax in stubs

docs/getting-started/installation.md, packages/safe-ds-vscode/README.md, packages/safe-ds-vscode/package.json
Disable inlay hints for assignee types by default. These were confusing for novices, who tried to type them out when they created their first assignments, given an example.
=> feat: disable inlay hints for assignee types by default

packages/safe-ds-cli/tests/cli/main.test.ts, packages/safe-ds-lang/src/language/safe-ds-module.ts, packages/safe-ds-lang/src/language/scoping/safe-ds-linker.ts, packages/safe-ds-lang/tests/resources/validation/linking/default error/main.sds, packages/safe-ds-lang/tests/resources/validation/linking/usage of python keywords/main.sds
Closes #1268
* Improve default error message of the linker.
* Add a default resolution to the message that might solve the issue (check spelling and imports).
* Add special resolutions, if users likely used Python keywords instead of Safe-DS keywords by accident (e.g. `True` instead of `true`).
=> feat: improve error messages from linker

docs/src/lexer/safe_ds_lexer/_safe_ds_lexer.py, packages/safe-ds-lang/src/language/grammar/safe-ds.langium, packages/safe-ds-lang/src/language/lsp/safe-ds-formatter.ts, packages/safe-ds-lang/src/language/validation/other/declarations/constraints.ts, packages/safe-ds-lang/src/language/validation/other/declarations/parameterBounds.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/formatting/declarations/constraints/greater than constraint with message.sdsdev, packages/safe-ds-lang/tests/resources/formatting/declarations/constraints/greater than or equal constraint with message.sdsdev, packages/safe-ds-lang/tests/resources/formatting/declarations/constraints/less than constraint with message.sdsdev, packages/safe-ds-lang/tests/resources/formatting/declarations/constraints/less than or equal constraint with message.sdsdev, packages/safe-ds-lang/tests/resources/grammar/declarations/constraints/good-greater than constraint with message.sdsdev, packages/safe-ds-lang/tests/resources/grammar/declarations/constraints/good-greater than or equals constraint with message.sdsdev, packages/safe-ds-lang/tests/resources/grammar/declarations/constraints/good-less than constraint with message.sdsdev, packages/safe-ds-lang/tests/resources/grammar/declarations/constraints/good-less than or equals constraint with message.sdsdev, packages/safe-ds-lang/tests/resources/scoping/parameter bounds/in annotation/main.sdsdev, packages/safe-ds-lang/tests/resources/scoping/parameter bounds/in enum variant in nested enum/main.sdsdev, packages/safe-ds-lang/tests/resources/scoping/parameter bounds/in global class/main.sdsdev, packages/safe-ds-lang/tests/resources/scoping/parameter bounds/in global function/main.sdsdev, packages/safe-ds-lang/tests/resources/scoping/parameter bounds/in method/main.sdsdev, packages/safe-ds-lang/tests/resources/scoping/parameter bounds/in nested class/main.sdsdev, packages/safe-ds-lang/tests/resources/scoping/parameter bounds/in segment/main.sdsdev, packages/safe-ds-lang/tests/resources/validation/other/declarations/constraints/message must only reference constant parameters/no message.sdsdev, packages/safe-ds-lang/tests/resources/validation/other/declarations/constraints/message must only reference constant parameters/strings.sdsdev, packages/safe-ds-lang/tests/resources/validation/other/declarations/constraints/message must only reference constant parameters/template strings.sdsdev, packages/safe-ds-lang/tests/resources/validation/other/declarations/parameter bounds/arguments must match parameter bounds/custom message.sdsdev, packages/safe-ds-vscode/syntaxes/safe-ds-stub.tmLanguage.json, packages/safe-ds-vscode/syntaxes/safe-ds.tmLanguage.json
Closes #1082
Constraints can now have custom error messages. These can be static strings or template strings that references constant parameter, e.g. in
```
@Pure fun f(
const p1: Int,
const p2: Int = -2,
) where {
p1 >= 0 else "This parameter must be non-negative.",
p2 > p1 else "p2 must be greater than p1, but p2 was {{ p2 }} and p1 was {{ p1 }}.",
}
```
=> feat: optional error messages for constraints

packages/safe-ds-vscode/package.json
Prevent accidental edits to built-in stubs by marking them as read-only by default. 
Unfortunately, if users specify their own value for the `files.readonlyInclude` setting, our default gets overwritten completely and stubs can be edited again. But it is the best we can do currently.
Scoping the setting to a Safe-DS language variant did not work. Stubs were still editable again afterward.
=> feat: prevent editing built-in stubs

packages/safe-ds-lang/src/resources/builtins/safeds/ml/nn/layers/DropoutLayer.sdsstub, packages/safe-ds-lang/src/resources/builtins/safeds/ml/nn/layers/MaxPooling2DLayer.sdsstub
Modifies the language stubs in preparation for the Custom Editor/Visualization PR #1243.
=> feat: categorize API elements

packages/safe-ds-lang/src/language/lsp/safe-ds-document-symbol-provider.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds-document-symbol-provider.test.ts
Placeholders that are defined directly inside the body of a pipeline or segment are now included in the outline. It is also possible to search for them using the command palette. For example, `@trainingSet` searches for any symbol named `trainingSet`, which now includes placeholders.
=> feat: show placeholders in outline

packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/tests/language/typing/type checker/isSubOrSupertypeOf.test.ts
Previously, the type checker incorrectly showed an error in the following program at the call marked with the arrow:
```
package bug
@Pure fun bug1(p: union<Int, String>)
@Pure fun bug2() -> r: literal<1, "">
pipeline bug3 {
val a = bug2();
bug1(a); // <----
}
```
This was caused because the quantifiers when comparing literal and union types were in the wrong order: 
- We checked whether there was an option in the union type that all constants of the literal type could be assigned to.
- Now we check whether, for each constant of the literal type, there is an option in the union type they could be assigned to.
=> fix: subtype check for literal and union types

packages/safe-ds-lang/src/language/typing/safe-ds-type-checker.ts, packages/safe-ds-lang/tests/language/typing/type checker/isSubOrSupertypeOf.test.ts
The type checker previously did not regard `literal<1, "">` as a subtype of `union<literal<1>, literal<"">`. This is fixed now.
=> fix: subtype check for literal and union types (part 2)

.github/dependabot.yml
Create a few groups for Dependabot to reduce the number of PRs it creates.
=> ci: dependency groups for Dependabot

packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/src/language/validation/types.ts, packages/safe-ds-lang/tests/helpers/nodeFinder.test.ts, packages/safe-ds-lang/tests/resources/typing/declarations/parameters/of block lambdas/that are passed as arguments/with type parameters.sdsdev, packages/safe-ds-lang/tests/resources/typing/declarations/parameters/of expression lambdas/that are passed as arguments/with type parameters.sdsdev, packages/safe-ds-lang/tests/resources/typing/expressions/block lambdas/that are passed as arguments/with type parameters.sdsdev, packages/safe-ds-lang/tests/resources/typing/expressions/expression lambdas/that are passed as arguments/with type parameters.sdsdev, packages/safe-ds-lang/tests/resources/validation/types/checking/arguments/with type parameters.sdsdev
The following code led to a stack overflow when inferring the type of the call marked with the arrow:
```
pipeline p {
g(() -> "1", (a) -> 2); // <-- here
}
@Pure
fun g<T>(
q2: () -> b: T,
q1: (a: T) -> (),
)
```
This PR fixes this.
=> fix: type inference for lambdas and their parameters

packages/safe-ds-lang/src/language/validation/other/types/callableTypes.ts, packages/safe-ds-lang/src/language/validation/other/types/getNodesToCheckForContext.ts, packages/safe-ds-lang/src/language/validation/other/types/unionTypes.ts, packages/safe-ds-lang/src/language/validation/safe-ds-validator.ts, packages/safe-ds-lang/tests/resources/validation/other/types/callable types/context/main.sdsdev, packages/safe-ds-lang/tests/resources/validation/other/types/callable types/context/nested.sdsdev, packages/safe-ds-lang/tests/resources/validation/other/types/union types/context/main.sdsdev, packages/safe-ds-lang/tests/resources/validation/other/types/union types/context/nested.sdsdev, packages/safe-ds-vscode/syntaxes/safe-ds-dev.tmLanguage.json, packages/safe-ds-vscode/syntaxes/safe-ds-stub.tmLanguage.json, packages/safe-ds-vscode/syntaxes/safe-ds.tmLanguage.json
Callable types and union types may now be used in type aliases. Usages of type aliases are checked like the type they alias, so a type alias referring to a union type may not be used as a result type.
=> fix: allow callable types and union types in type aliases

packages/safe-ds-lang/src/language/lsp/safe-ds-completion-provider.ts, packages/safe-ds-lang/tests/language/lsp/safe-ds.completion-provider.test.ts
The code-completion no longer suggests references (expression context) to type aliases.
=> fix: do not suggest references to type alias

packages/safe-ds-lang/src/language/typing/safe-ds-type-computer.ts, packages/safe-ds-lang/tests/resources/typing/declarations/type aliases/main.sdsdev
Fix an issue where the nullability of type aliases for nullable types was lost.
=> fix: handling of aliases of nullable types
